### ISSUE TITLE
openssl in qemu 

### ISSUE THREAD

**Issue by srjrjjr** [OP-TEE/optee_client#112]
Hi All,

I want to use Openssl libraries from the client(host) side. How to get the libraries and headers into a QEMU client system? I can induvidually compile the libs using the toolchains under optee-qemu/toolchains/aarch32/bin/arm-linux-gnueabihf. However I need toexport the libraries and header to the OP-TEE client. What is the way to do this? How can I include sources as well? Which build script should I change?

Where to copy the "openssl " folder that I have built?

Thanks,
Tera

**Comment by jbech-linaro** [comment]
Hi,

Basically [this](https://github.com/linaro-swg/gen_rootfs/blob/master/filelist.txt) file needs to be updated. We are doing that dynamically when building OP-TEE, i.e. we add "our" files to that file by creating another file and concatenate them together. All that magic by picking up the files and creating folders etc are done in [this](https://github.com/OP-TEE/build/blob/master/common.mk#L388-L472) section in the common makefile.

What you are trying to achieve would have been much easier if we would have been using something like [Buildroot](https://buildroot.org/) by defaults (but currently we don't).

**Comment by Telltera** [comment]
But where should I physically copy the openssl sources and includes for QEMU environment?
How to build it? I tried looking at libyaml in common.mk. However there, only the libs are copied. What about the includes and sources?

**Comment by jbech-linaro** [comment]
You should build everything on your desktop machine using a cross compiler, just as we are building everything else that are in the root fs. When that has been done, you need to figure out what libraries etc are needed to be able to run a user space binary who has been linked against openssl. 

So let's say that you create a binary named `"foo"`, then you must
1. First compile OpenSSL for Arm.
2. Compile `foo` and link against the headers and binaries from step 1.
3. Add `foo` and all the libraries needed to our root fs (the files I mentioned in the previous post). If you want to now what libraries `foo` needs, then try `$ ldd foo` and it will tell you. I.e, take add all those files as separate new lines [here](https://github.com/OP-TEE/build/blob/master/common.mk#L471).
4. `$ make run` will rebuilt the root fs for you and populate it with the new files.

That is how it can be done in theory. I haven't work with OpenSSL myself using our simple rootfs so I can't say if this is sufficient or not. It might be that openssl itself has some dependencies to libraries, but then again `ldd` will let you know.

**Comment by Telltera** [comment]
Hi, I did steps one and two. I am stuck in the step 3. What are the relevant build files that I have to modify so that I can add the openssl libraries and sources and headers?

**Comment by Telltera** [comment]
Hi, I am almost there. I have modiefied common.mk and copied the binaries and libraries(I adapted the libyaml from benchmark-app for the ssl ones). However I am still stuck while porting the include files and sources. How can I include an directory/src folders to my Application in common.mk?

**Comment by Telltera** [comment]
Hi,

what I am trying to do is something alone these lines in common.mk:
filelist-tee-common: optee-client xtest optee-examples foo
	@echo "# filelist-tee-common /start" 				> $(fl)
	@echo "dir /lib/optee_armtz 755 0 0" 				>> $(fl)
	@echo "dir /lib/openssl 755 0 0" 				>> $(fl)
	cp -rp $(FOO_PATH)/openssl/out/* /lib/openssl/

Thanks!

**Comment by jbech-linaro** [comment]
Hi,

This part:
```bash
cp -rp $(FOO_PATH)/openssl/out/* /lib/openssl/
```
With that you are trying to copy files on your host machine (to your Linux distros file system)  and that is not what you want achieve, you want to specify where the files are on your computer and where they are supposed to end up in the root fs, i.e., CPIO pattern file syntax and example:
```bash
 file path_on_device path_on_local_pc 755 0 0
```
```bash
 file /bin/strace ${HOME}/strace 755 0 0
```
So, in your case, that would mean finding all the necessary libraries and add lines like this:
```bash
 file /lib/openssl_foo.lib $(FOO_PATH)/openssl/out/openssl_foo.lib 755 0 0 >> $(fl)
 file /lib/openssl_bar.lib $(FOO_PATH)/openssl/out/openssl_bar.lib 755 0 0 >> $(fl)
```
Etc ... and that would deploy all the openssl libs in the folder called `/lib`.

The client app that you have build who is linked against openssl, what output do you get from `ldd` (the Arm-version).

**Comment by Telltera** [comment]
Hi, thanks. I was hoping I can copy all the headers under openssl/include folder other than the libs and binaries of the compiled library. 
 With the 'file' command in common.mk I can only copy binaries or single files. However I need to copy multiple directories into the library folder. How can I achieve this?

I even chucked 'common.mk' and  tried my hand at directly modifying the **gen_rootfs/generate-cpio-rootfs.sh** script to create a new /usr/lib directory where I can copy the entire headers and libraries. However the whole 'make run' runs without errors but I fail to see these files in the QEMU.

**Comment by jbech-linaro** [comment]
> I was hoping I can copy all the headers under openssl/include folder

Why do you need the headers in the root fs for the device? Are you going to try to compile directly on the device? If that is what you are trying to do, then you will have the same headache with gcc etc. In that case I would strongly recommend to instead pick up a pre-created root fs (Linaro has a [few](https://releases.linaro.org/)) or do it with buildroot. It's a bit tricky though to make the root fs for build root, but I manged to [make something working](https://github.com/jbech-linaro/buildroot/commits/qemu_optee) not that long ago.

> With the 'file' command in common.mk I can only copy binaries or single files. However I need to copy multiple directories into the library folder. How can I achieve this?

There are all sorts of creative ways to achieve that, I added [this](https://github.com/OP-TEE/build/blob/master/common.mk#L429-L431) short snippet which basically finds all files ending with `*.ta` from a folder (includes sub folders). It's ugly and hard to read, but it gets the job done. I.e., doing something similar, but with another file-ending should work (and of course change the destination path).

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
