### ISSUE TITLE
A bug in TEEC_ReleaseSharedMemory causes stdin to be destroyed!

### ISSUE THREAD

**Issue by ademyankov** [OP-TEE/optee_client#118]
The code like this:
```
TEEC_SharedMemory inShm{};
TEEC_ReleaseSharedMemory(&inShm);
```
with `0`-ed `TEEC_SharedMemory` structure falls through all ifs and causes this line:
https://github.com/OP-TEE/optee_client/blob/3f16662284a69fdec97b1712064be94d1fed7ae7/libteec/src/tee_client_api.c#L774
to close the file descriptor `0` which is happened to be `stdin` or `'/dev/tty'`.

A simple workaround does the job, but it relies on internals which is not a very good idea:
```
TEEC_SharedMemory inShm{};
inShm.id = -1;
```

**Comment by etienne-lms** [comment]
You could consider releasing an unallocated sharedmem as a programming error.
Useless `TEEC_AllocateSharedMemory()` or `TEEC_RegisterSharedMemory()` have successfully returned, you're not expected to release a non registered reference.

Consider the following that is likely to fail:
```
void *ptr;
free(ptr);
```

**Comment by ademyankov** [comment]
Let's agree to disagree.

The code you wrote is a programming error, no doubt in that I agree, because ptr will have garbage
```
void *ptr;
free(ptr);
```
But this code:
```
void *ptr = NULL;
free(ptr);
```
is perfectly valid code. And the function `free` will simply take no actions.
So, my code:
```
TEEC_SharedMemory inShm{};
TEEC_ReleaseSharedMemory(&inShm);
```
is valid because even though the memory was not allocated, the structure was properly initialized. It's just  TEEC_ functions have different meaning of initialization, which is a library fault.

For example, in Microsoft WDK for all kernel objects and structures you have macros like:
```
WDKKernelObject kernelObject;
WDK_KERNEL_OBJECT_INITIALIZE_INSTANCE(&kernelObject);
```
And you have to use it if you want to have a defined behavior.

So, if TEEC_ code needs some kind of magic special initialization for its objects then the library must provide the way.

**Comment by etienne-lms** [comment]
i agree with 1 thing: you must call `free()` with a inited reference (at least inited to `NULL`).
Same, you cannot call `TEEC_ReleaseSharedMemory()` with an non inited reference.

Sadly, GPD TEE does not define a `TEEC_ResetSharedMemoryReferenceStructure()` and neither `memset(ref, 0, sizeof(...))` nor `memset(ref, -1, sizeof(...))` are reliable initialization for such structure.

**Comment by ademyankov** [comment]
Ok, I see what you are saying about the standard.

Allowing to pass NULL into free is not a standard either but rather a convention, a convenient convention that the API designers agreed on. What I mean is there is nothing to prevent you guys to provide a macro to initialize an instance of SharedMemoryReferenceStructure.

It looks like I have to go with a facade to wrap this API around.
 
Ok, you can mark it as not a bug, suggestion or whatever and close it.

Thanks!

**Comment by etienne-lms** [comment]
We'll consider the suggestion, sure thanks.

**Comment by jenswi-linaro** [comment]
C99 standard says:
*The free function causes the space pointed to by ptr to be deallocated, that is, made
available for further allocation. If ptr is a null pointer, no action occurs. ...*
