### ISSUE TITLE
About how can Android system application  use  optee client API in the future

### ISSUE THREAD

**Issue by dracular1983** [OP-TEE/optee_client#120]
Hi All,

Currenttly, the treble architecture of Android P, have a lot of restrictions . for example, libary linker, socket between system and vendor .
Once a system service want to use the op-tee client api, it will face the problem.Maybe we can use hidl service to deal with this . But it still will be some problem about sharememory and struction  inforation which need to be passed between process.
I notice op-tee is doing some work about the AOSP . Will you have a plan to design a standard hidl interface for the gp client api？

Thanks

**Comment by vchong** [comment]
Hi,

I'm not sure if treble applies here? Treble defines a standard interface for the hardware/hal (vendor) but the client api lives above the OS framework.

You'd just use JNI to call the api from the apks. See https://github.com/linaro-swg/optee_android_manifest/issues/31 for some discussions about it.

**Comment by vchong** [comment]
Continue discussion on https://github.com/linaro-swg/optee_android_manifest/issues/31. Closing.
