### ISSUE TITLE
Message Queue support in QEMU

### ISSUE THREAD

**Issue by divneil** [OP-TEE/optee_client#129]
Hi,

I am testing some code sequence in QEMU, which involves message queues.
I am getting msg queue id = 0, and any `msgsnd()` is failing on that with error code = 22 (EINVAL)
However, `msgrcv()` is waiting. Can you please help in suggesting some solution. Thanks

**Comment by jenswi-linaro** [comment]
We have no such functions in either OP-TEE OS or for the TAs so I can only assume you're talking about posix message queues in normal world user space. I don't see the connection with OP-TEE.

**Comment by divneil** [comment]
Yes, its POSIX message queues. I thought of putting in optee_client as it runs in normal world.

For the issue, I wanted to close it before any response - (but I got one) - as I screwed up at my end. Apologies for not being thorough this time.
