### ISSUE TITLE
how to find version number of the optee_client in the source?

### ISSUE THREAD

**Issue by vsivanagulu** [OP-TEE/optee_client#130]

**Comment by vsivanagulu** [comment]
We are able to run optee-xtest on linux4.9 and optee-os3.0.0. But we are not able to run optee-xtest on linux4.12.4 with optee_os3.0.0 or 3.2.0. I thought trying to run with various versions of optee_os, optee_client and optee_xtest would give us some progress.
We want to run optee on linux.4.12.4. We get the below crash logs when tried to run it.
[bootlog-crash.txt](https://github.com/OP-TEE/optee_client/files/2282144/bootlog-crash.txt)

**Comment by jforissier** [comment]
To avoid compatibility problems, please make sure that all OP-TEE sources (optee_os, optee_client, optee_test) are "in sync". The OP-TEE Git repositories are tagged with the OP-TEE release, so if you want to try OP-TEE 3.2.0, you should checkout tag 3.2.0 in all the Git repositories.

As for the Linux kernel, the more recent the better, generally speaking. Upstream 4.12+ should be a good starting point (it contains the OP-TEE driver).

HTH.

**Comment by vsivanagulu** [comment]
Thanks for your hints @jforissier, I tried to run kernel 4.9 and 4.12 with optee versions 3.0.0 and 3.2.0.
linux 4.9 works with both but linux 4.12 fails in both. I enabled optee and disabled "Hardware cripto devices" in both.
I observed that the optee_os is not getting loaded into same location in memory for both the kernels. Refer the below screenshot.
![vi_diff_4-9and4-12](https://user-images.githubusercontent.com/21194696/44094782-bcd0dc58-9ff4-11e8-9289-02ac598cd18f.png)
Please let me know if I need to make a new query thread since the version question is actually answered.
