### ISSUE TITLE
Using TEE Client APIs from a kernel module

### ISSUE THREAD

**Issue by jiria** [OP-TEE/optee_client#135]
Hello,

As part of my projects, I would like to be able to consume TEE Client APIs from another kernel module. As per Global Platform TEE Client API Specification, there is no assumption taken on whether the TEE Client APIs are exposed to the privileged and/or user layers of the rich environment. Have you considered exposing the TEE Client APIs from the TEE kernel module directly? 

And second to that, if you were heavily opposed to exposing TEE Client APIs directly inside the kernel, do you have a recommendation as to how to execute a TA from another kernel module?

Regards,
Jiri

**Comment by vchong** [comment]
You can use this: https://github.com/linaro-swg/linux/commit/fc17132dbccc1d7ab18883c902d450877e561546

It's been submitted upstream as well: https://lkml.org/lkml/2018/7/9/92

**Comment by jiria** [comment]
Thank you, this has worked very well.
