### ISSUE TITLE
Client is build without LFS support

### ISSUE THREAD

**Issue by Emantor** [OP-TEE/optee_client#140]
I ran into a Large File Support issue today, where the OP-TEE client could not detect the creation of the /data directory correctly, since the stat64() call was used.
The fix inside my BSP was to append `-D_FILE_OFFSET_BITS` to the optee_client CFLAGS.
The [GLIBC Feature page](https://ftp.gnu.org/old-gnu/Manuals/glibc-2.2.3/html_node/libc_13.html) describes all the macros, you might prefer another fix for the optee_client Makefile.
Please let me now and I will create a Pull request with your prefered fix.

**Comment by jforissier** [comment]
Hi @Emantor,

Thanks for reporting this. At first glance, I would say go for `-D_FILE_OFFSET_BITS=64` in the optee_client Makefile.
