### ISSUE TITLE
Keeping shared memory alive

### ISSUE THREAD

**Issue by AlessandroVisintin** [OP-TEE/optee_client#148]
Hi everyone,

For attestation purposes I am trying to keep a shared memory alive during the entire execution of a trusted application.

From the client part I am using TEEC_RegisterSharedMemory() method for registering it and from there it is never closed, i.e. I don't call the TEEC_ReleaseSharedMemory() method.

At first I am able to reach the shared binary.
The problem arises when I share other parts of memory for communication purposes. It seems like the new shared memories overwrite the old one, meaning that the address I originally saved has the same value but inside of it there is no more the original shared binary but the new one.

Is there a way to keep the shared memory available throughout the entire execution? Already tried to globally declare the Shared Memory object but it is still not working.

Edit:
I read on the issues that the shared address passed as parameter during an InvokeCommand() is valid only throughout the scope of that execution and will not be valid after that.

Probably I should change my question to: is there any way to make a shared memory accessible during different invocations? And if this is not achievable, could it be possible to get the normal world address value to see if the buffer shared is always the same?

Thank you very much.

**Comment by etienne-lms** [comment]
Hi,
From GPD TEE specs, shared memory is only available to a TA is the TA is invoked with the shared memory references by one of the 4 availabe invocation parameters (a (typed with one of `TEE_PARAM_TYPE_MEMREF_{INPUT|OUTPUT|INOUT}`).

That means that if you invoke a TA with a shm reference, and invoke the TA again without the shm reference as param, the second invocation will not see to shared buffer.

Note that if you invoke a TA with the very same shm reference as parameter, it is possible that the TA will see the very same shm buffer with different (virtual) addresses for each of both invocation.

**Comment by jforissier** [comment]
It is also possible that "shared memory" is not actually shared but copied in/out.
See the GP TEE Client API Specification v1.0 section *3.2.5 Memory References*.

I don't think you can rely solely on the GP API semantics to do what you are trying to achieve.

**Comment by AlessandroVisintin** [comment]
Ok thank you very much.

The application I am developing is just for experimental purposes so I could just assume that an eventual attacker cannot tamper the attestation address.

Just to be sure: is there any place in the middle of OP-TEE code in which I could retrieve the normal world address of the buffer shared? Because in that way I could just compare it with the one I am expecting to see if somebody has changed it.

Thank you very much again.
