### ISSUE TITLE
Passing a NULL memref buffer in TEEC_Operation

### ISSUE THREAD

**Issue by pokitoz** [OP-TEE/optee_client#149]
Hello!

I have a TA application that might take a NULL memory reference as an input:

```
TEEC_Operation operation = {0};
TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INPUT,
                                      TEEC_NONE,
                                      TEEC_NONE,
                                      TEEC_NONE);
}

operation.params[0].tmpref.buffer = buffer;
operation.params[0].tmpref.size = buffer_length;
```

buffer and buffer_length are two parameters that are given as input and the buffer can be NULL. If the buffer is NULL, then the size is 0.

When I try to use `Inkove_Command() ` the TEE seems to fail. The application stalls. If I try to restart the application I get:
`3: ERR [3026] TEES:main:663: failed to find an OP-TEE supplicant device`

After looking at `4.3.7. TEEC_TempMemoryReference` in the `TEE_Client_API_Specification-V1.0_c`, I saw:

> buffer is a pointer to the first byte of a region of memory which needs to be temporarily
registered for the duration of the Operation. This field can be NULL to specify a null Memory
Reference.

I was wondering if I miss-understood the documentation or if this is indeed an issue. I found that strange to see the application that stopped.
Let me know if you need any more information, debug logs,..

**Comment by jforissier** [comment]
> If I try to restart the application I get:
> `3: ERR [3026] TEES:main:663: failed to find an OP-TEE supplicant device`

Does `tee-supplicant` crash? If it does, this obviously needs debugging (run `tee-supplicant` with `gdb`).

**Comment by jbech-linaro** [comment]
> Does `tee-supplicant` crash? If it does, this obviously needs debugging (run `tee-supplicant` with `gdb`).

@pokitoz : for that [this](https://optee.readthedocs.io/building/devices/qemu.html#gdb-normal-world) might give some guidance.

**Comment by pokitoz** [comment]
Thanks for your answers. The issue was not related to Optee-Client and was my mistake. It seems that I was updating the size of the buffer to 1 instead of keeping it to 0 :confounded: . So it was trying to share a memory buffer starting at address 0 which I don't have access to..
For tee-supplicant failing it was because the test framework I am using was trying to relaunch the application that was already opened.. Anyway, at least I learned how to debug tee-supplicant.
