### ISSUE TITLE
Typo in tee_client_api.h

### ISSUE THREAD

**Issue by esemeniuc** [OP-TEE/optee_client#159]
https://github.com/OP-TEE/optee_client/blob/1f8f9abe4a31abd7b7490a7ddd9bbe812c92d5af/public/tee_client_api.h#L348

**Comment by jbech-linaro** [comment]
Thanks for reporting @esemeniuc , [do you want to provide a fix for it](https://optee.readthedocs.io/general/contribute.html)? Otherwise we can do it also.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_client/pull/164
