### ISSUE TITLE
optee client port for u-boot

### ISSUE THREAD

**Issue by a21152** [OP-TEE/optee_client#167]
Is there already an effort to port OP-TEE client to u-boot and other bootloader environments?

**Comment by jenswi-linaro** [comment]
There's already a sort of OP-TEE client in u-Boot, see include/tee.h in the u-Boot source tree.

**Comment by a21152** [comment]
Awesome! Where is the avb TA stored to make it available for loading from
u-boot?

**Comment by jenswi-linaro** [comment]
It's kept as an early TA (CFG_EARLY_TA), that is, it's loaded from a binary blob in the OP-TEE binary.

**Comment by a21152** [comment]
I see. Thanks!
