### ISSUE TITLE
TA calls by multi-threaded host application

### ISSUE THREAD

**Issue by piachristel** [OP-TEE/optee_client#168]
I have implemented a host application which starts multiple threads (1, 2, 4 or 8). Each of the threads redoes a so called `query` method/transaction during a fixed amount of time. This `query` transaction includes:
1. an initialization of a context (`TEEC_InitializeContext`)
2. an opening of a session (`TEEC_OpenSession`)
3. 2 calls towards the TA loaded by the session (`TEEC_InvokeCommand`) 
4. a closure of the session 
5. a finalization of the context 

I have runned the host application
a. emulated with QEMU (`SMP` = 4, `CFG_NUM_THREADS` = 4) and 
b. on the Raspberry Pi (`CFG_NUM_THREADS` = 4)
Other from what I expect, the throughput (number of `query` transaction per second) does not double (or nearly double) with a doubling of threads. In case a. we only have an increase of the throughput by factor 1.2 from 1 to 2 threads, and in case b. the throughput even decreases from 1 to 2 threads.

As far as I have seen from the code, the `tee-supplicant` is multi-threaded and cannot be the bottleneck. Is there any part of OP-TEE which does provide a bottleneck for multi-threaded host application (each having its own context and session) calling the secure world?

Thanks in advance for any pointers.

**Comment by jforissier** [comment]
Hi @piachristel,

TA execution is serialized in secure world, unless the client targets  different TA instances (for that you need a multi-instance TA).

**Comment by piachristel** [comment]
Hi @jforissier,

Thanks for replying!

My TA is actually a multi-instance TA. In the `user_ta_header_define.h`, I have
```
#define TA_FLAGS TA_FLAG_EXEC_DDR
```
So my TA only defines the `TA_FLAG_EXEC_DDR` (which is deprecated from what I have just read in the doc...). From the documentation, I understand that if `TA_FLAGS` does not set `TA_FLAG_SINGLE_INSTANCE,` the single instance property is false and therefore we have a multi-instance TA (as in my case).

So this then cannot explain the bottleneck?

**Comment by jforissier** [comment]
Do you create several contexts?

**Comment by piachristel** [comment]
Yes, each thread has its own context.

**Comment by jbech-linaro** [comment]
In the debug prints you should be able to see the "core id" ([here](https://github.com/OP-TEE/optee_os/blob/master/lib/libutils/ext/trace.c#L130)), example right after the first colon `D/TC:0 0 ...`". If you have prints enabled (+ that enabled), will you see numbers corresponding to all 4 cores? Ideally all cores on the system should be "busy" to leverage all threads I think.

**Comment by jforissier** [comment]
Do you see that the kernel is using all CPUs? (`dmesg | grep "Booted secondary processor"`).

Could you check if the AES crypto test scales properly on your board? Here is what I get on my HiKey960:

```
# time sh -c "for i in 1; do { xtest --aes-perf -s 131072 -n 50000 -w 0 & } ; done ; wait 2>&1 | grep real
real    0m 4.78s
# time sh -c "for i in 1 2; do { xtest --aes-perf -s 131072 -n 50000 -w 0 & } ; done ; wait 2>&1 | grep real
real    0m 5.06s
# time sh -c "for i in 1 2 3; do { xtest --aes-perf -s 131072 -n 50000 -w 0 & } ; done ; wait 2>&1 | grep real
real    0m 5.35s
# time sh -c "for i in 1 2 3 4; do { xtest --aes-perf -s 131072 -n 50000 -w 0 & } ; done ; wait 2>&1 | grep real
real    0m 6.17s
```

**Comment by jenswi-linaro** [comment]
`TEEC_OpenSession()` is mostly serialized with other calls to `TEEC_OpenSession()`, but `TEEC_InvokeCommand()` should not be much so.
Try `xtest 1013` which in the end reports the level of concurrency achieved.

**Comment by piachristel** [comment]
@jenswi-linaro You say that `TEEC_OpenSession()` is mostly serialized with other calls to `TEEC_OpenSession()`. Does that also hold in my case:
- with multi-instance TA
- where each thread in the host application uses its own context and sessio
?

**Comment by jenswi-linaro** [comment]
Yes, there's a mutex in OP-TEE which is held during the loading of a TA. We're aiming to replace it with more fine grained synchronization at some point.

**Comment by piachristel** [comment]
@jenswi-linaro Do you maybe have a pointer to the code where this mutex during TA loading is hold?

**Comment by jenswi-linaro** [comment]
This is the piece of code I was talking about:
https://github.com/OP-TEE/optee_os/blob/6ff2e3f10cab2a086ebb159bdab6ccc497aa50ab/core/kernel/tee_ta_manager.c#L630-L661

**Comment by piachristel** [comment]
Thank you all for your hints and pointers.
It helped to explain my bottleneck!
