### ISSUE TITLE
cancel_id seems unused

### ISSUE THREAD

**Issue by c-auger** [OP-TEE/optee_client#173]
I try to understand how operations can be cancelled by reading the code of the client.
But from what I read in the code:

- `TEEC_RequestCancellation()` sets `cancel_id` field to `0`, and only sets the session identifier,
- `TEEC_OpenSession()` does not set `cancel_id` and the session identifier is an output, not an input,
- `TEEC_InvokeCommand()` does not set `cancel_id` and only sets the session identifier.

Thus I have the feeling that:

- `TEEC_OpenSession()` should not be cancellable as carrying nothing to identify it,
- `TEEC_InvokeCommand()` is cancellable by using the session identifier, but this is a little weak, as it does not fully identify the operation (if a thread invocates A then B, and a parallel thread tries to cancel A, then it might cancel B instead unless extraneous synchronisation is added),
- `cancel_id` field is never used.

Is there anything that I did not see?

**Comment by jenswi-linaro** [comment]
I think you're correct in your analysis. Patches are welcome to fix (and test) this.

**Comment by c-auger** [comment]
I am a little busy at this moment, and I see no trivial fix. Generation of `cancel_id` should probably be done by the application, and increment some hidden counter (in `libutee` ?), in a way such that two parallel threads will not produce the same `cancel_id` (having collisions would be bad, I think). And Linux kernel would have to "patch" it to avoid having two different unrelated applications generating the same `cancel_id`.

I will think of it in some weeks.

**Comment by jenswi-linaro** [comment]
Hi @c-auger, I agree that the fix will not be trivial. I'm starting to doubt if whatever fix is done will be worth it in the end, especially if there's going runtime overhead in the common case. Also note that invoke on the same session is going to be serialized in secure world so there's only going to be at most one active invoke at a time to cancel.
