### ISSUE TITLE
How does OP-TEE handle UUIDs for identifying Client Applications?

### ISSUE THREAD

**Issue by frennet** [OP-TEE/optee_client#182]
Hi,
I have a question regardings OP-TEE's implementation of the login methods specified by GlobalPlattform. When a CA calls TEEC_OpenSession, it can choose a login method by setting a value for parameter connectionMethod. The TA can retrieve the login method by accessing the property gpd.client.identity which is of type TEE_Identity. TEE_Identity contains an UUID for identifying the CA. The TEE Internal Core API Specification states that this UUID is set by the Rich Excecution Environment and therefore it is implementation-specific.

So my question is: How does OP-TEE handles the UUID? I haven't found any documentation. For example: When a CA calls TEEC_OpenSession with connectionMethod=TEEC_LOGIN_APPLICATION, which UUID the TA can expect?

**Comment by jforissier** [comment]
Hi @frennet ,

I have not tested but I very much suspect that the client UUID is zero. In [`TEEC_OpenSession()`](https://github.com/OP-TEE/optee_client/blob/3.8.0/libteec/src/tee_client_api.c#L483-L552) we can see that `arg->uuid` is set but not `arg->clnt_uuid` (the structure of `arg` is defined [here](https://github.com/OP-TEE/optee_client/blob/3.8.0/libteec/include/linux/tee.h#L287-L317)).

**Comment by frennet** [comment]
Maybe it is good idea to not set arg->clnt_uuid in TEEC_OpenSession() since it is called in the process context of the CA. GPD states: "When gpd.client.identity is not equal to TEE_LOGIN_TRUSTED_APP, then the Rich OS is responsible for ensuring that the Client Application cannot tamper with its own properties." So I thing the Kernel Tee Driver should set the Client UUID. 

The question still is: Is the Client-UUID set anywhere (and how)? Or is this feature not implemented?

**Comment by jforissier** [comment]
My previous answer was a convoluted way of saying: not implemented.

**Comment by frennet** [comment]
What's about the login method TEEC_LOGIN_USER? Is this method implemented by OP-TEE respectively by the Linux TEE driver?

**Comment by jforissier** [comment]
The Linux driver has no way to map a user ID to an UUID so if you use TEEC_LOGIN_USER in your client application, the TA will receive a zero UUID.
