### ISSUE TITLE
Why/where is stuff in optee_client/out/ copied to out-br/build/optee_client-1.0/out/?

### ISSUE THREAD

**Issue by jbech-linaro** [OP-TEE/optee_client#184]
I've noticed a weird thing that I cannot explain by reading our makefiles (in this git and in build.git). If you start out from a clean build environment and build once, then you'll end up with
```bash
$ find out-br/build/optee_client-1.0/ -maxdepth 1 -type d
out-br/build/optee_client-1.0/
out-br/build/optee_client-1.0/tee-supplicant
out-br/build/optee_client-1.0/libteec
out-br/build/optee_client-1.0/scripts
out-br/build/optee_client-1.0/public
out-br/build/optee_client-1.0/CMakeFiles
out-br/build/optee_client-1.0/libckteec
```

Nothing strange (notice **no** out-folder), but if you for example then do
```bash
$ mkdir -p optee_client/out && echo "foobar" > optee_client/out/joakim.h
```

Then rebuild, then you see that "joakim.h" is in out-br.
```bash
$ find out-br/build/optee_client-1.0/ -maxdepth 1 -type d
out-br/build/optee_client-1.0/
out-br/build/optee_client-1.0/tee-supplicant
out-br/build/optee_client-1.0/libteec
out-br/build/optee_client-1.0/scripts
out-br/build/optee_client-1.0/public
out-br/build/optee_client-1.0/out
out-br/build/optee_client-1.0/CMakeFiles
out-br/build/optee_client-1.0/libckteec

$ find out-br/build/optee_client-1.0/ -name "joakim.h"
out-br/build/optee_client-1.0/out/joakim.h
```

Where the heck does our makefiles find and do the copy from `optee_client/out/` to `out-br/build/optee_client-1.0/out`? [This](https://github.com/OP-TEE/optee_client/blob/master/Makefile#L130) doesn't seem to be called and I believe it shouldn't since it's not (I hope?) used by Buildroot. [This](https://github.com/OP-TEE/optee_client/blob/master/public/CMakeLists.txt#L6-L21) maybe? I've done some printing with those variables, but doesn't look like that either.

Why do I care? Well, the system have tricked me on this when trying to use files built by buildroot. I have other ways to avoid this, but I find it rather annoying that I cannot figure out why it behaves like this. So, I'm throwing out the question to someone else who might have an answer to it :)

**Comment by jforissier** [comment]
I think Buildroot first copies the whole source project into out-br/build before building. From https://buildroot.org/downloads/manual/manual.html:

> LIBFOO_SITE_METHOD determines the method used to fetch or copy the package source code [...]
> * local for a local source code directory. [...] Buildroot copies the contents of the source directory into the package’s build directory.

**Comment by jbech-linaro** [comment]
Aha, that might be the case and would explain it. I had no idea that Buildroot worked like that, but it seems like a possible explanation, thanks!

**Comment by jenswi-linaro** [comment]
It's due to this:
https://github.com/OP-TEE/build/blob/f854c16c5c213cd6af1ec0568d4ae77116d79f51/br-ext/package/optee_client/optee_client.mk#L3

Yes, @jforissier's explanation is correct. That's how we can select a version of the git using repo.

**Comment by jbech-linaro** [comment]
Thanks for clarification/confirmation Jens!
