### ISSUE TITLE
TEEC_RegisterSharedMemory and zero-copy

### ISSUE THREAD

**Issue by frennet** [OP-TEE/optee_client#189]
Hi, the GlobalPlattform TEE Client API Specification states that TEEC_RegisterSharedMemory "SHOULD attempt to transfer data in to the TEE without using copies, if this is possible on the underlying implementation, but MUST fall back on data copies if zero-copy cannot be achieved."

Do you know if zero-copy is realized in OP-TEE's implementation of TEEC_RegisterSharedMemory?

**Comment by etienne-lms** [comment]
hello @frennet,
When OP-TEE dynamic shared memory  is enabled in optee_os (`CFG_CORE_DYN_SHM=y`), yes, zero copy is realized for buffers registered through `TEEC_RegisterSharedMemory()`.
