### ISSUE TITLE
Can tee-supplicant be design like a daemon process.

### ISSUE THREAD

**Issue by prz999** [OP-TEE/optee_client#19]
Hi,

I think that every time I running tee-supplicant should added a & is not convenience, I think it would be better to change it to running as a daemon process automatically. As I know it is just fork a subprocess and exit its parent. But I 'm not sure is this you design on purpose.

Regards,
Ruizhi

**Comment by jforissier** [comment]
Hi @akbarsaleemt,

tee-supplicant provides normal world services to the secure side of OP-TEE, such as filesystem access, locking primitives (mutexes), etc.

**Comment by akbarsaleemt** [comment]
thank you .But how SMC occur.how FIQ interrupt raised

**Comment by akbarsaleemt** [comment]
pleaase explain the flow of following 
User space                  Kernel                   Secure world
      ~~~~~~~~~~                  ~~~~~~                   ~~~~~~~~~~~~
   +--------+                                             +-------------+
   | Client |                                             | Trusted     |
   +--------+                                             | Application |
      /\                                                  +-------------+
      || +----------+                                           /\
      || |tee-      |                                           ||
      || |supplicant|                                           \/
      || +----------+                                     +-------------+
      \/      /\                                          | TEE Internal|
   +-------+  ||                                          | API         |
   + TEE   |  ||            +--------+--------+           +-------------+
   | Client|  ||            | TEE    | OP-TEE |           | OP-TEE      |
   | API   |  \/            | subsys | driver |           | Trusted OS  |
   +-------+----------------+----+-------+----+-----------+-------------+
   |      Generic TEE API        |       |     OP-TEE MSG               |
   |      IOCTL (TEE_IOC_*)      |       |     SMCCC (OPTEE_SMC_CALL_*) |
   +-----------------------------+       +------------------------------+

**Comment by jforissier** [comment]
This should help: https://github.com/OP-TEE/optee_os/issues/2168

**Comment by akbarsaleemt** [comment]
Thank you verymuch

**Comment by akbarsaleemt** [comment]
can we implement multiple trusted worlds on single core .Is there any process?

**Comment by jbech-linaro** [comment]
@akbarsaleemt you're asking whether it is possible to run more than a single TEE implementation from different TEE vendors on a single core? I'd say that, no it is not "possible" with the current Arm architecture. The reason for the quotes is that almost everything is possible, it's just whether it makes sense and whether it is worth doing that and that is where I think this idea fails.
