### ISSUE TITLE
A potential integer overflow

### ISSUE THREAD

**Issue by HuKeping** [OP-TEE/optee_client#197]
As per https://github.com/OP-TEE/optee_client/blob/master/tee-supplicant/src/tee_supplicant.c#L506

Will this creates a potantial integer overflow?
```
static bool write_response(int fd, union tee_rpc_invoke *request)
{
	struct tee_ioctl_buf_data data;

	memset(&data, 0, sizeof(data));

	data.buf_ptr = (uintptr_t)&request->send;
	data.buf_len = sizeof(struct tee_iocl_supp_send_arg) +
		       sizeof(struct tee_ioctl_param) *
				request->send.num_params;
	if (ioctl(fd, TEE_IOC_SUPPL_SEND, &data)) {
		EMSG("TEE_IOC_SUPPL_SEND: %s", strerror(errno));
		return false;
	}
	return true;
}
```

On 32bit CPU, line 506 seems like `__u64 = __u32 * __u32`

**Comment by jforissier** [comment]
> On 32bit CPU, line 506 seems like __u64 = __u32 * __u32

It is `__u64 = 8 + 32 * __u32` as far as I can tell. What could go wrong here?

**Comment by HuKeping** [comment]
@jforissier wouldn't the variable `b` be 0?
```
    __u32 a = 4294967295;
    __u64 b = 32 + 32 * a;
```

**Comment by jforissier** [comment]
Ah, I see what you mean now... a cast to `__u64` is missing, right?

```C
	data.buf_len = sizeof(struct tee_iocl_supp_send_arg) +
		       sizeof(struct tee_ioctl_param) *
				(__u64)request->send.num_params;
```

**Comment by HuKeping** [comment]
exactly @jforissier !

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_client/pull/198

Thanks for reporting. Feel free to add a `Reported-by: ...` to the PR if you like.

**Comment by HuKeping** [comment]
> Thanks for reporting. Feel free to add a Reported-by: ... to the PR if you like.

yes, please

**Comment by HuKeping** [comment]
#198 merged.

Closing.
