### ISSUE TITLE
soname `libckteec.so.ckteec` is wrong

### ISSUE THREAD

**Issue by ggardet** [OP-TEE/optee_client#213]
Soname `libckteec.so.ckteec` is wrong and should be `libckteec.so.0`.

**Comment by jforissier** [comment]
Agreed. Care to submit a patch?

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_client/pull/214

Note I have introduced the same variables we have in PR 171 (https://github.com/OP-TEE/optee_client/pull/171/commits/547aaf8cb4b734ee92c6e026e03e51c0d73312d9) for consistency.

@ggardet I have used your public identity (as shown on your GitHub profile) in a Reported-by: tag, I hope it's OK, if it's not just let me know and I'll remove it. Thanks!

**Comment by ggardet** [comment]
> #214

Thanks!

> Note I have introduced the same variables we have in PR 171 ([547aaf8](https://github.com/OP-TEE/optee_client/commit/547aaf8cb4b734ee92c6e026e03e51c0d73312d9)) for consistency.
> 
> @ggardet I have used your public identity (as shown on your GitHub profile) in a Reported-by: tag, I hope it's OK, if it's not just let me know and I'll remove it. Thanks!

That's fine.

**Comment by jforissier** [comment]
PR merged, closing. Thanks for reporting!
