### ISSUE TITLE
PKCS#11 implementation plan

### ISSUE THREAD

**Issue by anisyanka** [OP-TEE/optee_client#220]
Hi,

I'm interested in your pkcs11 implementation, namely libcktee in REE and pkcs11-ta as a backend in TEE.

In Aurora OS project (Russian fork of [Sailfish OS](https://sailfishos.org/)) we plan to use pkcs11 as an interface between REE and TEE keystore and TEE cryptography.

I see that some of pkcs11-functions are just stubs, namely:
 - C_GenerateKey/C_GenerateKeyPair
 - C_FindObjects
 - C_SignInit/C_Sign/C_SignUpdate/C_SignFinal
 - C_SeedRandom/C_GenerateRandom

...that return 'CKR_FUNCTION_NOT_SUPPORTED'.

Could you please tell us about your pkcs11 implementation plan?
Or maybe we can help you to implement them?

Thank you!

**Comment by jforissier** [comment]
Hi @anisyanka,

These functions are in the Linaro OP-TEE Contributions (LOC) tasks 6, 11, 12 and 15, see 
 https://projects.linaro.org/projects/LOC/issues/. Certainly @ruchi393 @jbech-linaro @etienne-lms @jenswi-linaro can comment further :)

**Comment by ruchi393** [comment]
Thanks @jforissier for providing the details. 

@anisyanka , given below is the PKCS#11 work which we plan to work on for coming months :
https://projects.linaro.org/projects/LOC/issues/  
LOC-6 - PKCS#11 - Basic secure object support
LOC-12 - PKCS#11 - Key management functions
LOC-15 - PKCS#11 - Signature and MAC functions

This covers most of the API's you have mentioned above except the Random Numbers one (LOC-11), which is not planned for now. 

You can check "PKCS#11 support in OP-TEE (LOC-21)" for our overall plan wrt PKCS#11 implementation. Please note that only LOC-6,12 and 15 are currently planned in coming months. For the remaining activities listed in LOC-21 , we will revisit the plans again next year. Meanwhile, you are welcome to contribute to help accelerate the development.

I hope this helps. 

Regards,
Ruchika

**Comment by anisyanka** [comment]
Thank you for the detailed answer and links!
Also I want to discuss the already implemented function - `C_CreateObject()`.

This call is handled in pkcs11-ta as `TEE_CreatePersistentObject()`.
But how to control access to this object?

What do you think about saving a CA UUID together with the object?
We can use `TEE_GetPropertyAsIdentity()` to get the uuid.

**Comment by etienne-lms** [comment]
`TEE_CreatePersistentObject()` is only used for persistent objects.
If the object is not persistent, it is visible only from the client, so CA that owns the session.
If the object is persistent then it is visible from the user or public, upon is object attributes.
At least from my understanding.

Whereas how to restrict an object to user IDs/groups, that's another topic.
