### ISSUE TITLE
Reallocating shared memory from inside the TA?

### ISSUE THREAD

**Issue by mzombor** [OP-TEE/optee_client#222]
Hi there!

My application sends data with a known size to the TA using Shared Memory but the returned size is unknown. Because of this it's not really an option to create a return buffer for it as overestimating the size of the returned data and copying less isn't what I'm looking for, I'll need something more deterministic.

My question is, is there an option to reallocate the shared memory buffer to a bigger size from inside the TA and write data into the extended buffer? It would make creating place for the returned data much easier as the TA knows how much data was created and once the data is returned the Rich App can just read it from the end of the buffer.

I hope my question can be understood I'm happy to provide more info if it's a bit ... weird.

**Comment by jenswi-linaro** [comment]
> Hi there!
> 
> My application sends data with a known size to the TA using Shared Memory but the returned size is unknown. Because of this it's not really an option to create a return buffer for it as overestimating the size of the returned data and copying less isn't what I'm looking for, I'll need something more deterministic.

You can call the TA twice, first one time to get the required size of the buffer and then again to get the data.

> 
> My question is, is there an option to reallocate the shared memory buffer to a bigger size from inside the TA and write data into the extended buffer?

No

> It would make creating place for the returned data much easier as the TA knows how much data was created and once the data is returned the Rich App can just read it from the end of the buffer.

I guess that means that zero-copy isn't interesting for you use-case.

**Comment by mzombor** [comment]
I didn't  mention that the required size is only known after the process is completed. Based on this there's two scenarios that come to mind.  (three actually, with the third probably being the most elegant but also very unlikely it'd work)

> You can call the TA twice, first one time to get the required size of the buffer and then again to get the data.  

I hope I'm getting this right: I'd call the TA which would complete the process and create the output. I could then save the output into a buffer inside the TA while returning the required size of an output buffer. After the Rich App sees the returned size it would create another shared memory object (one with the needed size) and call the TA once more to get the output?  This would probably be efficient as the process doesn't run twice, but can I create a buffer like that inside the TA?

The other scenario is that I call the TA to complete the process, after which the required size is known. Return the size to the Rich Side and call the TA again with the now known size and a correctly allocated output buffer into which the process can now place the output? This would effectively run the process twice and slow things down significantly, but takes care of the whole "where do I keep the output data" problem.

The third option is that there's a way (that I'm not aware of, because I'm dumb) to pass the control back to the Rich App and have the TA wait until it receives another, bigger shared memory object?

> I guess that means that zero-copy isn't interesting for you use-case.  

How could I use it in this context? Generally want to know, I'm not totally familiar with the concept :(

**Comment by jenswi-linaro** [comment]
There's no realloc of shared memory parameters passed to TAs, instead there's the pattern of calling twice. That can get a bit inefficient of you throw away the result after the first call. If you instead save the partial state when returning from the first call you can resume it in the second call.

Zero copy: If you register the memory location where you want to have the result in the end, the TA can put the result at the desired memory address directly instead of needing another memcpy() to get it in the right position.

**Comment by mzombor** [comment]
How can I save this partial state? Should I save it in a Persistent Object inside the Secure Storage and load it up from there when calling the TA the second time? If there's another way can you point me to an example?

**Comment by jenswi-linaro** [comment]
To start with in a global variable. If you need more finesse you can use `sessionContext` passed to `TA_InvokeCommandEntryPoint()`.

**Comment by mzombor** [comment]
How can I store variable length (possibly large) data in the sessionContext? I couldn't really find anything in the docs. If I save the data in a global buffer for later use, will I be able to access it during subsequent calls to the TA?

**Comment by jforissier** [comment]
> If I save the data in a global buffer for later use, will I be able to access it during subsequent calls to the TA?

Yes, and you can also use `TEE_Malloc()`.

**Comment by mzombor** [comment]
Does this mean, that the TA is bound to the CA by it's session and the TA (and it's memory mappings) remain alive until the session is closed? Based on my prior knowledge I believe so, just making sure I understand everything correctly, I really don't wanna mess anything up this time.

**Comment by jforissier** [comment]
Global variables, the heap (`TEE_Malloc()`)and most memory mappings [1] are bound to the TA instance. Therefore they remain alive until the instance is destroyed. You can access them in successive invocations in a session. You can even share them across sessions in case of a multisession single instance TA.

[1] except temporary mappings created for memref parameters

**Comment by mzombor** [comment]
Thank so much! Both @jforissier  and @jenswi-linaro. This was a great help :)
