### ISSUE TITLE
teec_free_temp_refs will close the wrong shm->fd (0) when teec_shm_alloc failed 

### ISSUE THREAD

**Issue by HeJyunYan** [OP-TEE/optee_client#224]
`teec_pre_process_operation` will return an error code of `teec_pre_process_tmpref` derrectly when it failed (such as allocate a very large size of SHM). In this situation, the `shm->id` are still zero. It result in to wrong error handling. When `TEEC_ReleaseSharedMemory` is called in function `teec_free_temp_refs`, it may close a wrong `fd` 0 since the `shm->id` is not -1  (the initial value is zero).

**Comment by HeJyunYan** [comment]
Is #225 OK? :)

**Comment by jenswi-linaro** [comment]
Good catch! :-)
