### ISSUE TITLE
RPMB access

### ISSUE THREAD

**Issue by RNNord2** [OP-TEE/optee_client#227]
Hi. I'm having trouble using eMMC RPMB in an i.MX6 system. This is not actually an optee-client issue, but since optee-client can communicate with RPMB i'm taking a chance that someone here might recognize the issue and give me a hint where to look for the cause. I have the boot flow SPL -> optee-os -> U-boot -> Linux. The SW versions used are:

optee (all parts): 3.7.0 (with patches to read HUK at from CAAM at start-up)
SPL & U-boot: 2019.07
Linux: 4.14.149

Configurations:
optee-client: Disabled RPMB_EMU in tee-supplicant makefile
optee-os: CFG_RPMB_FS=y, CFG_RPMB_WRITE_KEY=y, CFG_RPMB_FS_DEV_ID=2 (since mmc2 is our eMMC device)

The issue is, we can successfully program a key and read the RPMB counter from U-boot, using the mmc command. Once Linux is started however, RPMB communication attempts fails, and it fails in a similar fashion regardless if it is mmc-utils or optee-client making the ioctl calls: It seems the responses from the ioctl calls are empty, i.e. no response data is provided on the given address (the data in the response frame remains whatever it was prior to the ioctl call).

If anyone have any idea what might cause this problem, a hint is very much appreciated.

**Comment by jforissier** [comment]
Hi @RNNord2,

I don't know the i.MX6 specifics but I can hopefully give a couple of general recommendations.

- Does the RPMB Linux driver initialize properly? You should see logs mentioning `rpmb` on boot I think, as the kernel detects the storage and the partitions.
- Can you find some RPMB stuff under `/dev`?
- `CFG_RPMB_FS_DEV_ID` needs to reflect the number of the device as seen under `/dev`.

**Comment by RNNord2** [comment]
Hi @jforissier, 

thank you for replying. I didn't yet check the startup logs in detail, but I will. Anyway, I can see /dev/mmcblk2rpmb as expected.

**Comment by jforissier** [comment]
> Hi @jforissier,
> 
> Anyway, I can see /dev/mmcblk2rpmb as expected.

Hmm... then I suppose the startup logs probably don't matter much, but check for errors or suspect messages anyways.

**Comment by ldts** [comment]
@RNNord2 do you have this fix in U-boot https://github.com/u-boot/u-boot/commit/2464b229b5ab281d8698aa0f4d4de6d4d3fabf7d#diff-787c06de6a88b1cffb491b97eeb348956c442fff7bdd750ea222752fc6eff497 ? the commit message might perhaps give you a hint of what could be happening, I am not sure.

**Comment by RNNord2** [comment]
@ldts , thank you for you reply. As I'm aiming to access rpmb only from user space (mmc utils or optee-client), and as even a simple rpmb read counter attempt fails from user space, the issue is not a U-boot vs. kernel endianess issue. In my case, the rpmb ioctl response frames are not pupulated by the underlying ioctl code.

**Comment by RNNord2** [comment]
My problem seems to be solved by applying a number of kernel patches converting rpmb from a block device to a character device, starting with this one. After applying this patch, optee-client can write the rpmb key, and I can write data to and read data from rpmb using mmcutils.

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v4.14.202&id=37d58689dfdd068c2f15f90d573f8e93fe28cf86
