### ISSUE TITLE
CMake and Makefile builds are different

### ISSUE THREAD

**Issue by rossburton** [OP-TEE/optee_client#228]
The Makefile builds a versioned shared library, but the CMake build just installs a static library.

Notably, the keyword `SHARED` is missing from the `add_library` calls.

**Comment by rossburton** [comment]
Also, the sonames of the libraries are different.  If I explicitly pass `-DBUILD_SHARED_LIBRARIES=ON` and compare Make vs CMake builds:

`optee-client-dev: FILELIST: removed "/usr/lib/libteec.so.1.0", added "/usr/lib/libckteec.so.0 /usr/lib/libteec.so.1.0.0 /usr/lib/libckteec.so.0.1.0"`

**Comment by jforissier** [comment]
> The Makefile builds a versioned shared library, but the CMake build just installs a static library.
> 
> Notably, the keyword `SHARED` is missing from the `add_library` calls.

..,.nd yet:

```
optee_repo_qemu_v8$ find out-br/target -name libteec.so\* | xargs ls -l
lrwxrwxrwx 1 jerome jerome    12 Oct 28 16:50 out-br/target/usr/lib/libteec.so -> libteec.so.1
lrwxrwxrwx 1 jerome jerome    16 Oct 28 16:50 out-br/target/usr/lib/libteec.so.1 -> libteec.so.1.0.0
-rwxr-xr-x 1 jerome jerome 14312 Oct 28 16:50 out-br/target/usr/lib/libteec.so.1.0.0
```

Could SHARED be the default in my environment and not in yours? :thinking:

**Comment by rossburton** [comment]
Since discovered that I can pass `-DBUILD_SHARED_LIBRARIES=ON`, presumably you're doing that?

**Comment by jforissier** [comment]
> Since discovered that I can pass `-DBUILD_SHARED_LIBRARIES=ON`, presumably you're doing that?

Indeed, and it's apparently coming from Buildroot:
```
package/pkg-cmake.mk:           -DBUILD_SHARED_LIBS=$$(if $$(BR2_STATIC_LIBS),OFF,ON) \
```
(`BR2_STATIC_LIBS` does not seem to be set anywhere).

I think the more fundamental question is, why not allow a static library?

**Comment by rossburton** [comment]
I'd suggest that the `add_library()` should build both static and shared by default.

**Comment by eaaltonen** [comment]
The simplest approach is to build `SHARED` in CMake (_also included in_ [118f980478c8f04b](https://github.com/OP-TEE/optee_client/pull/259/commits/118f980478c8f04b4635ccf0c4ccacaa1d569d52)). Building both is of course possible, but takes a longer `CMakeLists.txt`.

**Comment by rossburton** [comment]
Still builds static by default in cmake builds.

**Comment by jenswi-linaro** [comment]
@rossburton, would you mind proposing a PR to fix the problem in your use case?
