### ISSUE TITLE
Intermingled logs on RPI3B+

### ISSUE THREAD

**Issue by Jayanth94** [OP-TEE/optee_client#234]
Hi, I am working on RaspberryPi-3B+ board. I tested the optee-examples and it works completely fine. But I see the logs are intermingled. The print messages from the client app side is not printed correctly . Could someone explain how to solve this ?

**Comment by Jayanth94** [comment]
Hi  jbech-linaro,
Sorry I shud have formatted it correctly. 
The Client App source contains printf ( ) functions for printing on serial console and on the TA side we have IMSG for logging. Is this  causing any problem. ?
I have attached the serial output here. 

D/LD:  ldelf:168 ELF (8aaaf200-2450-11e4-abe2-0002a5d5c51b) at 0x40069000
F/TC:? 0 trace_syscall:128 syscall #6 (syscall_close_ta_session)
D/TC:? 0 tee_ta_close_session:492 csess 0x10179340 id 1
D/TC:? 0 tee_ta_close_session:512 Destroy session
D/TA:  TA_CreateEntryPoint:40 has been called
D/TA:  TA_OpenSessionEntryPoint:69 has been called
I/TA: Hello World!
F/TC:? 0 plat_prng_add_jitter_entropy:72 0xB2
**Invoking**D/TA:  inc_value:106 has been called
 **TA to incremen**tI/TA: Got value: 42 from NW
 **42**
I/TA: Increase value to: 43
**TA incre**D/TC:? 0 tee_ta_close_session:492 csess 0x10179b40 id 1
**mented** vD/TC:? 0 tee_ta_close_session:512 Destroy session
**alue to** I/TA: Goodbye!
**43**
D/TA:  TA_DestroyEntryPoint:51 has been called
D/TC:? 0 destroy_context:292 Destroy TA ctx (0x10179ae0)

This is the issue. From the TA side the logs are printed correctly but not on the Client App .

**Comment by jbech-linaro** [comment]
No proble

> Hi @jbech-linaro ,
> Sorry I shud have formatted it correctly.

No problem.

The issue you're facing is well known and that **is** the behavior on devices with a single UART.

**Comment by vchong** [comment]
If you can find a way to ssh (or any other method of remote connection) to the board, then you can 'separate' the logs, i.e. printf() on ssh terminal and IMSG() on the serial/uart console.

**Comment by Jayanth94** [comment]
Hi @vchong 

Is there any instructions on achieving it . If it works , would be a working solution for my problem. 
As far as I understand, the OP-TEE porting on Raspberry Pi 3B+. 
Its quoted “OP-TEE developer builds” shall not be compared with full Linux distributions which supports “everything”. As a couple of examples, we don’t enable any particular drivers in Linux kernel, we don’t include all sorts of daemons, we do not include an X-environment etc.

I have even tried fetching the ip of the board but was not successful as I can read the following Uboot log.

U-Boot 2019.01-00093-gaac0c29d4b (Nov 16 2020 - 16:57:03 +0100)

DRAM:  948 MiB
RPI 3 Model B+ (0xa020d3)
MMC:   mmc@7e202000: 0, sdhci@7e300000: 1
Loading Environment from FAT... OK
In:    serial
Out:   serial
Err:   serial
**Net:   No ethernet found.**
starting USB...
USB0:   scanning bus 0 for devices... 4 USB Device(s) found
       scanning usb for storage devices... 0 Storage Device(s) found
Hit any key to stop autoboot:  0 
15073792 bytes read in 628 ms (22.9 MiB/s)

I am not sure is anything missing from the software perspective ( Ethernet cable was connected to board ) as I have followed all the steps mentioned in the documentation while building the OP-TEE. 

Would be really helpful if you can helpme out with this.

**Comment by vchong** [comment]
@Jayanth94 Do you have an eth interface on the buildroot (not u-boot) prompt? I don't have an rpi3 board, and sorry for giving you possibly false hope, but if there's no network access to the board then not sure if there's any other good way to separate the logs. As you've read on the documentation, network access isn't really part of OP-TEE development per se. The doc does also mention that "people (from Sequitur Labs) have successfully been able to add OP-TEE to Raspbian builds" so not sure if you can perhaps get some guide from them?

**Comment by Jayanth94** [comment]
Hi @vchong 
Welcome to Buildroot, type root or test to login
buildroot login: [    3.353440] dwc_otg_handle_wakeup_detected_intr lxstate = 2
[    3.662106] usb 1-1.1.1: new high-speed USB device number 4 using dwc_otg
[    3.762788] usb 1-1.1.1: New USB device found, idVendor=0424, idProduct=7800
[    3.774887] usb 1-1.1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    4.114434] libphy: lan78xx-mdiobus: probed
[    4.456364] random: crng init done

Welcome to Buildroot, type root or test to login
buildroot login: test
$ ipaddr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether b8:27:eb:86:ba:29 brd ff:ff:ff:ff:ff:ff

I have not configured Buildroot for ethernet support. The default built image shows the following.

**Comment by vchong** [comment]
I've not configured Buildroot for network access either. Try googling for 'buildroot configure network interfaces' and see if any results help. E.g. http://www.xappsoftware.com/wordpress/2013/07/04/how-to-configure-network-interfaces-in-a-buildroot-target.

**Comment by Jayanth94** [comment]
Thanks. I will try to configure and test it.

**Comment by vchong** [comment]
You're welcome. Not much help really. Good luck and please update if anything works.

**Comment by Jayanth94** [comment]
Hi @vchong,

After configuring the buildroot for network support and after adding the additional packages (ssh) now I am able to ssh on to my raspberrypi board from my host(Ubuntu). 
Could you please guide me on how to separate the logs on different terminals . I am not sure on how to achieve this. ('separate' the logs, i.e. printf() on ssh terminal and IMSG() on the serial/uart console). Thanks in advance.

**Comment by vchong** [comment]
@Jayanth94 That's great news you got it to work! Can you please share your patches by submitting a pull request to https://github.com/OP-TEE/build? It would be very useful to the other rpi3 users as well.

As for the separation of logs, there's nothing to do really. Just run your program (xtest, helloworld, etc) from your ssh terminal and you'll see the normal world logs (printf(), etc) on the ssh terminal and seucre world logs (IMSG(), etc) on the serial/uart console.

**Comment by Jayanth94** [comment]
Thanks. Its already handled and need no more changes (great:)). 
 
Well regarding your question. I would first explain what I have done so far and what I have tried out in order to ssh onto my board.
I have added these lines in the common.mk file  as OP-TEE has already mentioned that any package could be enabled by adding them in the common.mk file. So I just followed accordingly. 
BR2_PACKAGE_OPENSSH ?= y
BR2_PACKAGE_OPENSSH_SERVER ?= y              
BR2_PACKAGE_OPENSSH_KEY_UTILS ?= y

Linux Kernel Configuration:
I had referred to this page : http://www.cs.ait.ac.th/~on/O/oreilly/tcpip/tcpip/ch05_02.htm
CONFIG_NET_ETHERNET
Adds support for Ethernet hardware to the kernel. You need this for your Ethernet LAN.

I figured out that this was missing in the config file of the raspberry pi board. I added this for network support.

Then I even read in one of the blog on google https://www.mathworks.com/help/supportpkg/raspberrypi/ug/getting-the-raspberry_pi-ip-address.html that for assigning the ip statically steps were mentioned I followed it. So currently only IP assigned temporarily is working fine,so that I can connect to it via ssh .But if can use the ifconfig command to temporarily change the IP settings. Rebooting the board removes the ifconfig settings and restores the /etc/network/interfaces settings.

To change the IP settings temporarily, open a Linux command line. Enter ifconfig, the device id, a valid IP address, netmask, and the appropriate network mask. For example:

ifconfig eth0 192.168.45.12 netmask 255.255.255.0

(** Note : Still the IP is not being getting assigned via dhcp). 

Hope I have explained it correctly. If you feel ok with these changes  I will share my patch. Thank you.

**Comment by vchong** [comment]
> I have added these lines in the common.mk file as OP-TEE has already mentioned that any package could be enabled by adding them in the common.mk file. So I just followed accordingly.
> BR2_PACKAGE_OPENSSH ?= y
> BR2_PACKAGE_OPENSSH_SERVER ?= y
> BR2_PACKAGE_OPENSSH_KEY_UTILS ?= y

 Ok. This can be added to common.mk in build.git, and..

> Linux Kernel Configuration:
> I had referred to this page : http://www.cs.ait.ac.th/~on/O/oreilly/tcpip/tcpip/ch05_02.htm
> CONFIG_NET_ETHERNET
> Adds support for Ethernet hardware to the kernel. You need this for your Ethernet LAN.
> 
> I figured out that this was missing in the config file of the raspberry pi board. I added this for network support.

..this can probably go to kconfigs/rpi3.conf in build.git as well.

Then you can send a PR to build.git explaining what you're doing and why (e.g. refering to this issue). Hopefully the maintainers will accept the changes.

> 
> And for assigning IP temporarily, I followed this blog on google https://www.mathworks.com/help/supportpkg/raspberrypi/ug/getting-the-raspberry_pi-ip-address.html . So currently only IP assigned temporarily is working fine,so that I can connect to it via ssh .
> So we can use the ifconfig command to temporarily change the IP settings.
> Rebooting the board removes the ifconfig settings and restores the /etc/network/interfaces settings. So everytime IP has to be assigned to the RPI3 board.
> 
> To change the IP settings temporarily, open a Linux command line. Enter ifconfig, the device id, a valid IP address, netmask, and the appropriate network mask. For example:
> 
> After logging on to the raspberry pi board as root: Enter the following command.
> 
> ifconfig eth0 **192.168.45.12** netmask **255.255.255.0** ( Ip and netmask to be changed as per your local network settings)
> Hope I have explained it correctly. If you feel ok with these changes I will share my patch. Thank you.
> (** Note : Still the IP is not being getting assigned via dhcp).

For this, unless there's a way good way to automate these steps the build.git rpi3 Makefile that works in most general cases, you can probably just submit a PR here [1] that adds a section to the page to explain the manual steps needed to set this up.

[1] https://github.com/OP-TEE/optee_docs/blob/master/building/devices/rpi3.rst

**Comment by jforissier** [comment]
For the `eth0` config, perhaps it is just a matter of declaring the interface like for HiKey960? See https://github.com/OP-TEE/build/blob/3.11.0/br-ext/board/hikey960/overlay/etc/network/interfaces#L4
You could try to log in on the serial console, and add:
```
iface eth0 inet dhcp
```
...to `/etc/network/interfaces` then type `ifup eth0`.

**Comment by Jayanth94** [comment]
> For the `eth0` DHCP config, perhaps it is just a matter of declaring the interface like for HiKey960? See https://github.com/OP-TEE/build/blob/3.11.0/br-ext/board/hikey960/overlay/etc/network/interfaces#L4
> You could try to log in on the serial console, and add:
> 
> ```
> iface eth0 inet dhcp
> ```
> 
> ...to `/etc/network/interfaces` then type `ifup eth0`.



Hi @jforissier ,
Thanks for this information. I tried this and now the eth0interface is being assigned IP via dhcp.
But if the board is restarted IP is not assigned automatically on every restart.

I have saved the changes in the /etc/network/interfaces file.

But evrytime after reset I should enter ifup eth0. Then the IP is getting assigned. 
Is there a way to resolve this as well so that once the configurations saved should work everytime after reset. ?
Thanks

**Comment by jforissier** [comment]
@Jayanth94 I have not tried but it could be a matter of adding `auto eth0`:
```
auto eth0
iface eth0 inet dhcp
```

**Comment by Jayanth94** [comment]
> @Jayanth94 I have not tried but it could be a matter of adding `auto eth0`:
> 
> ```
> auto eth0
> iface eth0 inet dhcp
> ```

Nope. I have already added and tried this line **"auto eth0"**. Still the eth0  is not being assigned IP automatically on restart.

**Comment by jforissier** [comment]
OK, then I don't know. Input needed from a Buildroot expert ;-)

**Comment by Jayanth94** [comment]
> OK, then I don't know. Input needed from a Buildroot expert ;-)

No problem. Atleast I learnt something to assign IP via dhcp on a temporary basis. Thanks for all your inputs. I will try and if I find a way to assignIP via dhcp by default automatically on restart , I will update here.

**Comment by jayanthdc** [comment]
Thanks everyone @vchong @jforissier for all your answers. Since I have already sent the patch for this issue , I will close this ticket.
