### ISSUE TITLE
OPTEE TA- Crash 

### ISSUE THREAD

**Issue by Jayanth94** [OP-TEE/optee_client#243]
Hi All,

I am trying to run a trusted application and have allocated around 5mb stack and 1 mb heap space. 
I am getting this error and not sure about the root cause for this.

Can someone explain what is depicted in this log ? 

D/TC:2 0 abort_handler:518 [abort] abort in User mode (TA will panic)
E/TC:? 0 
E/TC:? 0 User mode data-abort at address 0x0 (translation fault)
E/TC:? 0  esr 0x92000005  ttbr0 0x2000010190040   ttbr1 0x00000000   cidr 0x0
E/TC:? 0  cpu #2          cpsr 0x40000100
E/TC:? 0  x0  0000000000077690 x1  00000000406b4120
E/TC:? 0  x2  0000000000000210 x3  0000000000000000
E/TC:? 0  x4  0000000000000000 x5  0000000000000000
E/TC:? 0  x6  0000000000000000 x7  00000000406b40cc
E/TC:? 0  x8  0000000000000035 x9  000000004009d418
E/TC:? 0  x10 0000000000000000 x11 0000000000000000
E/TC:? 0  x12 0000000000000000 x13 00000000406b4048
E/TC:? 0  x14 0000000000000000 x15 0000000000000000
E/TC:? 0  x16 0000000010123f70 x17 0000000000000000
E/TC:? 0  x18 0000000000000000 x19 00000000400b3fa4
E/TC:? 0  x20 0000000000000000 x21 00000000400a0000
E/TC:? 0  x22 0000000000000210 x23 000000004009d000
E/TC:? 0  x24 000000004009d547 x25 000000001a896779
E/TC:? 0  x26 00000000400b3f00 x27 0000000000000000
E/TC:? 0  x28 0000000000000000 x29 00000000406b4070
E/TC:? 0  x30 000000004008d220 elr 00000000400927e4
E/TC:? 0  sp_el0 00000000406b4070
E/LD:  Status of TA 37d82404-6269-4ab8-924e-76cd69fcfffb
E/LD:   arch: aarch64
E/LD:  region  0: va 0x40004000 pa 0x10800000 size 0x002000 flags rw-s (ldelf)
E/LD:  region  1: va 0x40006000 pa 0x10802000 size 0x008000 flags r-xs (ldelf)
E/LD:  region  2: va 0x4000e000 pa 0x1080a000 size 0x001000 flags rw-s (ldelf)
E/LD:  region  3: va 0x4000f000 pa 0x1080b000 size 0x004000 flags rw-s (ldelf)
E/LD:  region  4: va 0x40013000 pa 0x1080f000 size 0x001000 flags r--s
E/LD:  region  5: va 0x4008c000 pa 0x00001000 size 0x013000 flags r-xs [0]
E/LD:  region  6: va 0x4009f000 pa 0x00014000 size 0x115000 flags rw-s [0]
E/LD:  region  7: va 0x401b4000 pa 0x10938000 size 0x501000 flags rw-s (stack)
E/LD:   [0] 37d82404-6269-4ab8-924e-76cd69fcfffb @ 0x4008c000
E/LD:  Call stack:
E/LD:   0x00000000400927e4
E/LD:   0x000000004008d21c
E/LD:   0x000000004008d3f8
E/LD:   0x000000004008ce90
E/LD:   0x000000004008c2e8
E/LD:   0x000000004008c174
E/LD:   0x000000004008c090
E/LD:   0x0000000040092f78
E/LD:   0x0000000040090460
D/TC:? 0 user_ta_enter:176 tee_user_ta_enter: TA panicked with code 0xdeadbeef
D/TC:? 0 tee_ta_close_session:514 csess 0x10178b40 id 1
D/TC:? 0 tee_ta_close_session:533 Destroy session
D/TC:? 0 destroy_context:310 Destroy TA ctx (0x10178ae0)
E/TC:? 0 tee_ta_open_session:769 Failed. Return error 0xffff3024

Thanks

**Comment by jforissier** [comment]
Hi @Jayanth94,

It looks like you are dereferencing a NULL pointer at address 0x00000000400927e4. You may use `scripts/symbolize.py -d /path/to/ta/elf/file` and paste the crash dump to obtain the  source file and line numbers.

**Comment by Jayanth94** [comment]
Hi @jforissier ,

Many thanks. I will try to paste the crash and find the issue. 

Is there a way where in an IDE support is provided for Trusted Application support , so that we can step through the code if we encounter the crash and any other issue ?

**Comment by jbech-linaro** [comment]
> Is there a way where in an IDE support is provided for Trusted Application support , so that we can step through the code if we encounter the crash and any other issue ?

I gave a presentation ([OP-TEE debugging with GDB in QEMU](https://docs.google.com/presentation/d/1NEBZPrYqnjV55NOkJp_XQ7nGlOwDRuFb7z6cGO0Iboo/edit)) a couple of weeks ago. Unfortunately I had lots of problems with the connection and (full) screensharing, so only half of the talk got recorded and I couldn't show all windows at the same time. I'm going to re-record this offline at some point. But what is there can be found [here](https://linaro-org.zoom.us/rec/share/ZBiGd5Rq8bwarmOq6qffNMNLbBbFSteU5sjAIljPdziEibMIlm_FtjPY6qlHojxS.0J4iH3pLoNO4A4mS) (password: 3M@B*Bu7). That together with complementing deck should be able to help you understand how to debug the crash.

**Comment by jayanthdc** [comment]
> 3M@B*Bu

Thank you. I will go through it. Hope the procedure remains the same while debugging with other platforms apart from QEMU as I  am using raspberry Pi 3B+. ?

**Comment by jbech-linaro** [comment]
> Hope the procedure remains the same while debugging with other platforms apart from QEMU as I am using raspberry Pi 3B+. ?

Doing the same on RPi3B+ is much more tricky, since there you have to rely on OpenOCD and that is pretty unstable in general. I would recommend to port over your code to QEMU and do the work there and once complete, port it back to RPi3B+.

**Comment by jayanthdc** [comment]
> > Hope the procedure remains the same while debugging with other platforms apart from QEMU as I am using raspberry Pi 3B+. ?
> 
> Doing the same on RPi3B+ is much more tricky, since there you have to rely on OpenOCD and that is pretty unstable in general. I would recommend to port over your code to QEMU and do the work there and once complete, port it back to RPi3B+.

Ok. Thanks again for your suggestion.

**Comment by Jayanth94** [comment]
@jforissier @jbech-linaro ,
Thanks for your support.
