### ISSUE TITLE
Task Creation with OP-TEE OS.

### ISSUE THREAD

**Issue by jayanthdc** [OP-TEE/optee_client#246]
Hello All,

I am aware that multithreading is not supported by Trusted Applications.
But Is there a way for multitasking?
Can anyone please let me know if there are any API's OP-TEE OS provides for Task creation like { create , delete , set and get } functionalities.

Thanks in advance.

**Comment by jenswi-linaro** [comment]
> But Is there a way for multitasking?

Yes, each thread used for invoke or open session runs concurrently with synchronization where needed.

> Can anyone please let me know if there are any API's OP-TEE OS provides for Task creation like { create , delete , set and get } functionalities.

Threads are allocated automatically for each invoke or open session. There's no way of creating background threads without a counterpart in normal world.

**Comment by jayanthdc** [comment]
> > But Is there a way for multitasking?
> 
> Yes, each thread used for invoke or open session runs concurrently with synchronization where needed.
> 
So it means, if two applications from normal world invoke two different trusted applications , for each trusted application a trsuted thread is assigned from OP-TEE OS and these trusted threads run in parallel with synchronisation. Hope I have received your points correctly.
> > Can anyone please let me know if there are any API's OP-TEE OS provides for Task creation like { create , delete , set and get } functionalities.
> 
> Threads are allocated automatically for each invoke or open session. There's no way of creating background threads without a counterpart in normal world.

So it means a single trusted thread cannot create further tasks / threads during its execution. A thread gets assigned automatically whenevr normal world invokes a service from secure world.

**Comment by jenswi-linaro** [comment]
> > > But Is there a way for multitasking?
> > 
> > 
> > Yes, each thread used for invoke or open session runs concurrently with synchronization where needed.
> 
> So it means, if two applications from normal world invoke two different trusted applications , for each trusted application a trsuted thread is assigned from OP-TEE OS and these trusted threads run in parallel with synchronisation. Hope I have received your points correctly.

Correct.

> > > Can anyone please let me know if there are any API's OP-TEE OS provides for Task creation like { create , delete , set and get } functionalities.
> > 
> > 
> > Threads are allocated automatically for each invoke or open session. There's no way of creating background threads without a counterpart in normal world.
> 
> So it means a single trusted thread cannot create further tasks / threads during its execution. A thread gets assigned automatically whenevr normal world invokes a service from secure world.

Yes

**Comment by jayanthdc** [comment]
> > > > But Is there a way for multitasking?
> > > 
> > > 
> > > Yes, each thread used for invoke or open session runs concurrently with synchronization where needed.
> > 
> > 
> > So it means, if two applications from normal world invoke two different trusted applications , for each trusted application a trsuted thread is assigned from OP-TEE OS and these trusted threads run in parallel with synchronisation. Hope I have received your points correctly.
> 
> Correct.
> 
> > > > Can anyone please let me know if there are any API's OP-TEE OS provides for Task creation like { create , delete , set and get } functionalities.
> > > 
> > > 
> > > Threads are allocated automatically for each invoke or open session. There's no way of creating background threads without a counterpart in normal world.
> > 
> > 
> > So it means a single trusted thread cannot create further tasks / threads during its execution. A thread gets assigned automatically whenevr normal world invokes a service from secure world.
> 
> Yes



Thanks a lot for your answers.

**Comment by jayanthdc** [comment]
@jenswi-linaro Thanks for your support.
