### ISSUE TITLE
Dynamic Memory Allocation fails with dynamically loaded shared objects

### ISSUE THREAD

**Issue by jayanthdc** [OP-TEE/optee_client#249]
Hello @jforissier,

I have been trying to allocate memory using TEE_Malloc API in the dynamically loaded Shared Object.
Its returning NULL all the time.

Can't we allocate memory from dynamically loaded SharedObjects/ TA  ? I mean, the second TA which gets loaded using dlopen call from the first/Main Trusted App? 

I have defined heap size around 1MB in my main Trusted Application.

Kindly share your thoughts.
Thank you.

Best regards,
Jayanth

**Comment by jforissier** [comment]
That is unexpected indeed.

**Comment by jayanthdc** [comment]
> That is unexpected indeed.

Yeah.  I tested it couple of times by trying to allocate minimal memory around 100bytes just to see I wan't wrong before questioning here. But Indeed it turns to provide me a null pointer all the time.

I have allocated sufficient heap space from my main TA which loads this shared object TA. 
Also it was once clarified here in one of the other issues that the shared objects will be able to use the heap space alloted from the main trusted application . Based on this understanding I tried but it failed. 

Kindly let me know  is there something I could test and try out as I couldn't find any examples available to test my usecase.
Thanks in advance.

**Comment by jayanthdc** [comment]
Hi @jforissier ,

Is there a way to analyze and fix this issue or Is it something new , which needs to tested again. The issue is reproducible . Kindly let me know if there is something which I could try here . 

Thanks in advance
Jayanth

**Comment by jforissier** [comment]
Hi @jayanthdc,

I didn't have time to try and reproduce/debug this today. I am suspecting some kind of symbol resolution issue again.

Can you try cleaning `optee_os` (`rm -rf out`), your TA and your shared library, then rebuilding with `CFG_ULIBS_SHARED=y`? This will replace all user space static libraries (`libutils.a`, `libutee.a`...) with shared ones. In fact it might be the only sensible way to avoid multiply defined symbols and potentially inconsistent references.

To debug in more details you can run the TA with GDB (QEMU environment). It is not hard but not trivial either... You need to disable core and TA ASLR, observe at which addresses the TA and the shared library are mapped when the TA is run, then re-run after loading symbols into GDB with `add-symbol-file /path/to/ta/uuid.elf <ta_load_addr + 0x20>` and `add-symbol-file /path/to/shared/lib/uuid.elf <lib_load_addr>` and setting a breakpoint on `malloc()`.

In any case I will try to look into this tomorrow.

**Comment by jayanthdc** [comment]
> Hi @jayanthdc,
> 
> I didn't have time to try and reproduce/debug this today. I am suspecting some kind of symbol resolution issue again.
> 
> Can you try cleaning `optee_os` (`rm -rf out`), your TA and your shared library, then rebuilding with `CFG_ULIBS_SHARED=y`? This will replace all user space static libraries (`libutils.a`, `libutee.a`...) with shared ones. In fact it might be the only sensible way to avoid multiply defined symbols and potentially inconsistent references.
> 
> To debug in more details you can run the TA with GDB (QEMU environment). It is not hard but not trivial either... You need to disable core and TA ASLR, observe at which addresses the TA and the shared library are mapped when the TA is run, then re-run after loading symbols into GDB with `add-symbol-file /path/to/ta/uuid.elf <ta_load_addr + 0x20>` and `add-symbol-file /path/to/shared/lib/uuid.elf <lib_load_addr>` and setting a breakpoint on `malloc()`.
> 
> In any case I will try to look into this tomorrow.
Thanks a lot for your reply . Sure I will try to do the cleanup stuff and rebuild my OP-TEE OS again and test it. If I find any results I will update here.

**Comment by jayanthdc** [comment]
Hi @jforissier,

The issue is resolved . As you suggested I builded my optee-os using CFG_ULIBS_SHARED=y and then built my trusted application using those shared libraries.  
I was able to allocate memory using TEE_Malloc in my shared object/TA. 

D/LD:  ldelf:168 ELF (8aaaf200-2450-11e4-abe2-0002a5d5c51b) at 0x4007b000
D/LD:  ldelf:168 ELF (be807bbd-81e1-4dc4-bd99-3d363f240ece) at 0x400f9000
D/LD:  ldelf:168 ELF (71855bba-6055-4293-a63f-b0963a737360) at 0x40027000
D/LD:  ldelf:168 ELF (527f1a47-b92c-4a74-95bd-72f19f4a6f74) at 0x40050000
D/LD:  ldelf:168 ELF (87bb6ae8-4b1d-49fe-9986-2b966132c309) at 0x40093000
D/TA:  TA_CreateEntryPoint:44 has been called
D/TA:  TA_OpenSessionEntryPoint:73 has been called
I/TA: Hello World!
D/TA:  inc_value:114 has been called
D/TC:? 0 tee_ta_init_pseudo_ta_session:299 Lookup pseudo TA 3a2f8978-5dc0-11e8-9c2d-fa7ae01bbebc
D/TC:? 0 tee_ta_init_pseudo_ta_session:312 Open system.pta
D/TC:? 0 tee_ta_init_pseudo_ta_session:329 system.pta : 3a2f8978-5dc0-11e8-9c2d-fa7ae01bbebc
D/TC:? 0 tee_ta_init_session_with_context:609 Re-open TA 3a2f8978-5dc0-11e8-9c2d-fa7ae01bbebc
D/TC:? 0 ldelf_syscall_open_bin:140 Lookup user TA ELF e00508c9-4144-4be4-bcf2-616014c3e8e8 (Secure Storage TA)
D/TC:? 0 ldelf_syscall_open_bin:144 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:140 Lookup user TA ELF e00508c9-4144-4be4-bcf2-616014c3e8e8 (REE)
D/TC:? 0 ldelf_syscall_open_bin:144 res=0
D/LD:  ta_elf_add_library:1456 ELF (e00508c9-4144-4be4-bcf2-616014c3e8e8) at 0x4013f000
I/TA: Dlopen call success
**I/TA: Memory Allocation success : 0x40084070** 
D/TA:  add:48  Shared library print **** : 13
I/TA: ADDED RESULT IS : 13
I/TA: 
I/TA: Got value: 42 from NW
I/TA: Increase value to: 43
D/TC:? 0 tee_ta_close_session:514 csess 0x8734840 id 1
D/TC:? 0 tee_ta_close_session:533 Destroy session
I/TA: Goodbye!
D/TA:  TA_DestroyEntryPoint:55 has been called
D/TC:? 0 destroy_context:310 Destroy TA ctx (0x87347e0)
D/TC:? 0 tee_ta_close_session:514 csess 0x8730f30 id 1
D/TC:? 0 tee_ta_close_session:533 Destroy session
D/TC:? 0 tee_ta_close_session:514 csess 0x8730d40 id 2
D/TC:? 0 tee_ta_close_session:533 Destroy session

Many thanks for your timely input as it solved my problem with ease.

Best regards,
Jayanth

**Comment by jayanthdc** [comment]
Hi @jforissier,

I have a confusion in the dynamic memory allocation in the Secure World.
Considering qemu platfrom  : 
 * Partition memory into secure ROM, non-secure DRAM, secure "SRAM",
 * and secure DRAM.
 */
#define SEC_ROM_BASE			0x00000000
#define SEC_ROM_SIZE			0x00020000

#define NS_DRAM0_BASE			0x40000000
#define NS_DRAM0_SIZE			0x3de00000

#define SEC_SRAM_BASE			0x0e000000
#define SEC_SRAM_SIZE			0x00060000

#define SEC_DRAM_BASE			0x0e100000
#define SEC_DRAM_SIZE			0x00f00000

These are memory address ranges and size  : 

When I run my Trusted application in the Secure world, I assumed the dynamic memory allocation TEE_Malloc will be from the secure memory itself. I.e from **Secure DRAM. ( 0xe100000 - 0xf000000 ).** 
But the memory address was : **0x40084070** , when i used TEE_Malloc from TA, which is from the non secure DRAM. 
Is this the expected result ? Please correct me If I am wrong, as I am trying to understand better here.

Best  regards,
Jayanth

**Comment by jforissier** [comment]
You're mixing up physical and virtual addresses. The TA indeed lives in secure memory. `SEC_DRAM_BASE` (0xe100000) is a physical address. When the TA is mapped somewhere in this space, there is a corresponding virtual address range in which the heap is contained. 0x40084070 is a user-space virtual address.

To illustrate this, try calling `TEE_Panic(0)` in your TA after `TEE_Malloc()`. The dump will show the VA mappings for the "process" (TA) and you will see that the address returned by `TEE_Malloc()` should fall in the read/write range of executable `[0]` which is the TA main executable (it is in the `.bss` section actually).

**Comment by jayanthdc** [comment]
> You're mixing up physical and virtual addresses. The TA indeed lives in secure memory. `SEC_DRAM_BASE` (0xe100000) is a physical address. When the TA is mapped somewhere in this space, there is a corresponding virtual address range in which the heap is contained. 0x40084070 is a user-space virtual address.
> 
> To illustrate this, try calling `TEE_Panic(0)` in your TA after `TEE_Malloc()`. The dump will show the VA mappings for the "process" (TA) and you will see that the address returned by `TEE_Malloc()` should fall in the read/write range of executable `[0]` which is the TA main executable (it is in the `.bss` section actually).



D/LD:  ta_elf_add_library:1456 ELF (e00508c9-4144-4be4-bcf2-616014c3e8e8) at 0x401db000
I/TA: Dlopen call success
I/TA: Memory Allocation success : 0x4008e060 
E/TC:? 0 
E/TC:? 0 TA panicked with code 0x0
E/LD:  Status of TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b
E/LD:   arch: aarch64
E/LD:  region  0: va 0x40004000 pa 0x0e300000 size 0x002000 flags rw-s (ldelf)
E/LD:  region  1: va 0x40006000 pa 0x0e302000 size 0x008000 flags r-xs (ldelf)
E/LD:  region  2: va 0x4000e000 pa 0x0e30a000 size 0x001000 flags rw-s (ldelf)
E/LD:  region  3: va 0x4000f000 pa 0x0e30b000 size 0x004000 flags rw-s (ldelf)
E/LD:  region  4: va 0x40013000 pa 0x0e30f000 size 0x001000 flags r--s
E/LD:  region  5: va 0x40014000 pa 0x0e31a000 size 0x001000 flags rw-s (stack)
E/LD:  region  6: va 0x4005b000 pa 0x00000000 size 0x001000 flags r-xs [1]
E/LD:  region  7: va 0x4005c000 pa 0x00000000 size 0x002000 flags rw-s [1]
E/LD:  region  8: va 0x40085000 pa 0x00001000 size 0x001000 flags r-xs [0]
E/LD:  region  9: va 0x40086000 pa 0x00002000 size 0x009000 flags rw-s [0]
E/LD:  region 10: va 0x400d8000 pa 0x00000000 size 0x006000 flags r-xs [2]
E/LD:  region 11: va 0x400de000 pa 0x00005000 size 0x002000 flags rw-s [2]
E/LD:  region 12: va 0x400e5000 pa 0x00000000 size 0x042000 flags r-xs [4]
E/LD:  region 13: va 0x40127000 pa 0x00041000 size 0x005000 flags rw-s [4]
E/LD:  region 14: va 0x4014a000 pa 0x00000000 size 0x011000 flags r-xs [3]
E/LD:  region 15: va 0x4015b000 pa 0x00010000 size 0x005000 flags rw-s [3]
E/LD:  region 16: va 0x401db000 pa 0x00000000 size 0x001000 flags r-xs [5]
E/LD:  region 17: va 0x401dc000 pa 0x00000000 size 0x002000 flags rw-s [5]
E/LD:   [0] 8aaaf200-2450-11e4-abe2-0002a5d5c51b @ 0x40085000
E/LD:   [1] be807bbd-81e1-4dc4-bd99-3d363f240ece @ 0x4005b000
E/LD:   [2] 71855bba-6055-4293-a63f-b0963a737360 @ 0x400d8000
E/LD:   [3] 527f1a47-b92c-4a74-95bd-72f19f4a6f74 @ 0x4014a000
E/LD:   [4] 87bb6ae8-4b1d-49fe-9986-2b966132c309 @ 0x400e5000
E/LD:   [5] e00508c9-4144-4be4-bcf2-616014c3e8e8 @ 0x401db000
E/LD:  Call stack:
E/LD:   0x00000000401db39c
E/LD:   0x000000004008520c
E/LD:   0x0000000040158008
E/LD:   0x0000000040085320
D/TC:? 0 user_ta_enter:176 tee_user_ta_enter: TA panicked with code 0x0


Thank you verymuch. I just went with the address range . But now I am completely clear with this. 
The memory is allocated from the SECURE DRAM itself. 
Many thanks

**Comment by jayanthdc** [comment]
Hi @jforissier ,

I have been trying to load different shared objects via dlopen call and its working completely fine. But since the dlopen implementation with the OPTEE requires ( RTLD_NOW | RTLD_GLOBAL | RTLD_NODELETE ), the functions used in one of the dynamically loaded shared object aka TA is causing the symbol resolvement issue as the second shared object which also contains the same code which is being included in the first shared object.

As a result whenever I try to run the function from the second shared object it still points to the function from first shared object.
I feel its an issue related to  symbols and also since RTLD_GLOBAL is being used , it is always pointing to the function which is getting loaded via first shared object.

Is there a way to make the symbols local than global so that this issue could be resolved ? 
Kindly share your thoughts, as it helps me lot .
Thanks in advance.

Best regards,
Jayanth

**Comment by jforissier** [comment]
Hi @jayanthdc,

It is certainly possible to implement RTLD_LOCAL (i.e., not RTLD_GLOBAL) in ldelf. Would you consider giving it a try? It shouldn't be complicated at first glance. You would need to add a flag in `struct ta_elf` to tell if the binary makes its global symbols visible to others or not, and consider that flag in the `TAILQ_FOREACH()` loop in `ta_elf_resolve_sym()`.

A workaround would be to use different names for the symbols that are in conflict, or to make them `static` in C (the simplest option if they are used in a single file).

**Comment by jayanthdc** [comment]
> Hi @jayanthdc,
> 
> It is certainly possible to implement RTLD_LOCAL (i.e., not RTLD_GLOBAL) in ldelf. Would you consider giving it a try? It shouldn't be complicated at first glance. You would need to add a flag in `struct ta_elf` to tell if the binary makes its global symbols visible to others or not, and consider that flag in the `TAILQ_FOREACH()` loop in `ta_elf_resolve_sym()`.
> 
> A workaround would be to use different names for the symbols that are in conflict, or to make them `static` in C (the simplest option if they are used in a single file).

Thanks for your reply. I have already made them static const .
Still the issue persists.

**Comment by jayanthdc** [comment]
> > Hi @jayanthdc,
> > It is certainly possible to implement RTLD_LOCAL (i.e., not RTLD_GLOBAL) in ldelf. Would you consider giving it a try? It shouldn't be complicated at first glance. You would need to add a flag in `struct ta_elf` to tell if the binary makes its global symbols visible to others or not, and consider that flag in the `TAILQ_FOREACH()` loop in `ta_elf_resolve_sym()`.
> > A workaround would be to use different names for the symbols that are in conflict, or to make them `static` in C (the simplest option if they are used in a single file).
> 
> Thanks for your reply. I have already made them static const .
> Still the issue persists.

I will also try your suggestion. RTLD_LOCAL implementation.

**Comment by jayanthdc** [comment]
@jforissier ,

I tried this approach and it solved my problem.

I added :
**CFLAGS +=-fvisibility=hidden** 
in the makefile of the two shared objects( TA's) 
and kept __attribute__((visibility("default"))) for the function which was needed to be globally visible and it helped me.

**Comment by jforissier** [comment]
Thanks for the update. Sounds like a totally valid option.
