### ISSUE TITLE
Compile fail when export DEBUG=1

### ISSUE THREAD

**Issue by zhupg** [OP-TEE/optee_client#272]
Hello all,
There is spelling mistake in optee_client, when DEBUG=1, the compilation will fail.
```
  CC      src/pkcs11_api.c
In file included from src/pkcs11_api.c:10:0:
src/pkcs11_api.c: In function ‘C_Sign’:
src/pkcs11_api.c:969:36: error: ‘CKR_USER_NOT_LOGG_IN’ undeclared (first use in this function)
        CKR_SESSION_HANDLE_INVALID, CKR_USER_NOT_LOGG_IN,
```
It should be CKR_USER_NOT_LOGGED_IN.

I have created a pull request, please have a review, thanks.
https://github.com/OP-TEE/optee_client/pull/271

**Comment by etienne-lms** [comment]
Thanks a lot. See my comments in #271.
