### ISSUE TITLE
ioctl error handling in tee_client_api.c

### ISSUE THREAD

**Issue by Hussain1811** [OP-TEE/optee_client#284]
I have a doubt w.r.t the error handling in the function ioctl_errno_to_res().
In a nutshell, it means that we return TEEC_ERROR_GENERIC for all driver errors other than ENOMEM.

Should this error handling be refined a bit?
Reason for asking:
I have a scenario where i open a session --> close the session --> later call the invoke command

i end up in TEEC_ERROR_GENERIC instead of TEEC_ERROR_BAD_PARAMETERS. This is because the driver has returned some other error code than ENOMEM.

Ideally, in my scenario i need to be ending up with a TEEC_ERROR_BAD_PARAMETERS right?

**Comment by jenswi-linaro** [comment]
Makes sense. Would you like to create a pull request to fix this?

**Comment by Sadiq1811** [comment]
Hello @jenswi-linaro ,

Could you please check https://github.com/OP-TEE/optee_client/pull/285?
