### ISSUE TITLE
How to write file to RPMB FS?

### ISSUE THREAD

**Issue by jhcheon1000** [OP-TEE/optee_client#293]
Hi,
I am currently trying to write files (ex. certification...) to an actual rpmb device. (RPMB_EMU := 0)
In the secure_storage example, I confirmed that certain char arrays can be written to the rpmb area.
Then, is it possible to write a file?
If possible, how can I do that? And what is the maximum size of file?
Additionally, when I set both RPMB_FS and REE_FS to y, how does it work?

Currently I am working fine for all cases in xtest and optee_example (hello_world, secure_storage).

**Comment by jforissier** [comment]
Hello @jhcheon1000,

Please refer to the documentation at https://optee.readthedocs.io/en/latest/architecture/secure_storage.html.

A file in secure storage is called a "persistent object". It is created with `TEE_CreatePersistentObject()`. It can contain a stream of data (bytes) like a normal file on Linux etc, and it can also contain encryption keys.
The theoretical maximum size of a persistent object is `TEE_DATA_MAX_POSITION` (0xFFFFFFFF) but the size may be limited by the underlying storage (RPMB usually doesn't allow a very large capacity).
When both `CFG_RPMB_FS` and `CFG_REE_FS` are `y`, a Trusted Application may use different `strorageId` values:
- `TEE_STORAGE_PRIVATE` is the REE FS
- `TEE_STORAGE_PRIVATE_RPMB` is RPMB
- `TEE_STORAGE_PRIVATE_REE` is the REE FS.

**Comment by jhcheon1000** [comment]
Thanks for the quick reply!
