### ISSUE TITLE
How to compile a CA in REE?

### ISSUE THREAD

**Issue by StephQAZ** [OP-TEE/optee_client#294]
Hi, I am a new one in OP-TEE, and I have some confusion about the OP-TEE client. I just feel confused that whether I can compile my CA in REE?

In other words, I've successfully booted my Rpi3 with Raspbian os and OP-TEE os, and I can run the optee_examples, such as hello_world and secure_storage. And I just wonder can I build my CA in Rpi3 instead of building in my PC(ubuntu 16.04)?

I've tried this by writing a .c file with #include <tee_client_api.h>, but I failed to compile this file.
I run this command: ` $ gcc -o helloworld helloworld.c`

and the error log is 
----------------------------------------------------------------
fatal error: tee_client_api.h: No such file or directory"
 #include <tee_client_api.h> 
                ^~~~~~~~~~~~~
----------------------------------------------------------------
It seems that I can't include <tee_client_api.h> in my Rpi3.

So can anyone tell me that how to compile a CA in REE?  @jenswi-linaro @jforissier 

Kindly share your thoughts.
Thank you.

Best regards,
Steph

**Comment by jenswi-linaro** [comment]
You need to copy tee_client_api.h from the optee_client git into /usr/include or wherever you expect to find it on your system. That should hopefully be enough.

**Comment by StephQAZ** [comment]
@jenswi-linaro 
Thank you for your reply. 
I have copied tee_client_api.h to my include path, and there is no error log like 'No such file of directory'. Thank you for fixing my problem. But I have a new error, when I try to run `gcc -o helloworld helloworld.c`, that occurred another error：
---------------------------------------------------------------------
/usr/bin/ld: 1: /usr/bin/ld: /bin: Permission denied
/usr/bin/ld: 2: /usr/bin/ld: Syntax error: "(" unexpected
collect2: error: ld returned 2 exit status
---------------------------------------------------------------------

Do you know what can I do ?

Thank you.

Steph
