### ISSUE TITLE
Questions about libckteec and OpenSSL

### ISSUE THREAD

**Issue by tprrt** [OP-TEE/optee_client#301]
Currently, I successfully use libckteec.so with pk11cs-tool and openssl to perform crypto operations.

Moreover, I would like clarification on two points:
- Is it possible to manage (initialize, finalize...) PKCS#11 tokens directly from openssl or a third-party application is required, like pk11cs-tool?
- From openssl, it seems not possible to perform operations when PKCS#11 URI using some attributes, like the slot number. Are there any limitations compared to the RFC7512?

**Comment by etienne-lms** [comment]
Hi @tprrt,

> Is it possible to manage (initialize, finalize...) PKCS#11 tokens directly from openssl or a third-party application is required, like pk11cs-tool?

As far as I can tell, openssl does not provide interface to intiialize a PKCS#11 token (set SO, User PINs,  etc...) or generate and import an key into the PKCS#11 token. Therefore OpenSC developped pkcs11-tool util (IIUC).
Once you have a ready pkcs#11 token, you can use openssl with the pkcs11 engine from OpenSC.

> From openssl, it seems not possible to perform operations when PKCS#11 URI using some attributes, like the slot number. Are there any limitations compared to the RFC7512?

With openssl pkcs11 engine, you need to use the token label to identify a specific pkcs11 token. Slot number is not supported.
Check in [OpenSC libp11](https://github.com/OpenSC/libp11).
