### ISSUE TITLE
'tee-supplicant -d' may return before supplicant is ready

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_client#314]
Commit https://github.com/OP-TEE/optee_client/commit/523d50bdede6c9046b1e4c0bd09a8c7122ab96c2 changed the order of the calls to `open_dev()` and `daemon()` in `tee-supplicant`. As a result, there is no guarantee that `tee-supplicant -d` returns after the device is opened. Which means, if a kernel module is loaded immediately after the supplicant is started (`tee-supplicant -d; modprobe some_module`) the module may try to perform TEE operations via the kernel client API before `tee-supplicant` is ready, and fail. Note that user-space clients always wait for the supplicant while in-kernel clients do not (see [here](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/tee/tee_core.c?h=v5.19#n117) and [here](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/tee/tee_core.c?h=v5.19#n1128)), so this is not a problem for user-space clients.

Practical use case: the firmware TPM module loaded from initramfs, see https://gitlab.com/Linaro/trustedsubstrate/meta-ledge-secure/-/merge_requests/1/diffs?commit_id=ebd825ca35e6c8fdf76e3e2751f968ed51130138.

@parport0 any idea on how to fix this? Unfortunately, `daemon()` calls `_exit()` after forking so there is not much we can do after the call.

**Comment by jenswi-linaro** [comment]
The first tee-supplicant process must wait for some checkpoint in from the forked-off daemon process before exiting.

**Comment by jforissier** [comment]
@jenswi-linaro I agree, I will propose something, hopefully not too complicated.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_client/pull/315
