### ISSUE TITLE
libteec function "mmap_paddr" mmap size problem

### ISSUE THREAD

**Issue by kanyuelei** [OP-TEE/optee_client#318]
in libteec function "mmap_paddr"：

code：
    offset = (off_t)paddr % getpagesize();
    page_addr = (off_t)(paddr - offset);
    hw_addr = (intptr_t *)mmap(0, size, PROT_READ|PROT_WRITE,
                    MAP_SHARED, devmem, page_addr);
   return (hw_addr + offset);

Question：
mmap  size should be “size+offset”？

**Comment by jenswi-linaro** [comment]
Yes, that makes sense.

**Comment by jforissier** [comment]
@kanyuelei will you propose a patch?
