### ISSUE TITLE
Type definitions in tee_client_api.h violate the GlobalPlatform TEE Client API spec

### ISSUE THREAD

**Issue by tchebb** [OP-TEE/optee_client#348]
### Background

The [GlobalPlatform TEE Client API Specification v1.0][spec], which OP-TEE's libteec adheres to, defines API objects as structures visible to and allocated by the user rather than as opaque pointers.

[spec]: https://higherlogicdownload.s3.amazonaws.com/GLOBALPLATFORM/transferred-from-WS5/TEE_Client_API_Specification-V1.0_c.pdf

While some of those objects—like `TEEC_UUID`—are fully specified by the spec, others—specifically `TEEC_Context`, `TEEC_Session`, `TEEC_SharedMemory`, and `TEEC_Operation`—end with an `imp` field of a type defined by the implementation. For example, `TEEC_SharedMemory` is specified as follows:
```c
typedef struct
{
	void* buffer;
	size_t size;
	uint32_t flags;
	<Implementation-Defined Type> imp;
} TEEC_SharedMemory;
```

And this is what the spec has to say about the `imp` field (emphasis mine):
> Implementations are allowed to extend some of the data structures defined in this specification to include a single field of *implementation-defined* type, named `imp`. **Implementations MUST NOT add new fields outside of `imp`**.

### The problem

But here's how we currently define our version of `TEEC_SharedMemory`:
https://github.com/OP-TEE/optee_client/blob/8533e0e6329840ee96cf81b6453f257204227e6c/public/tee_client_api.h#L291-L306

We don't have a field named `imp` at all! We instead put multiple implementation-specific fields right in the struct, **in direct violation of the spec.** I imagine we did this because it seemed an immaterial distinction, but I've found a case where it makes a difference for me as a user of libteec:

### Why it matters

I'm currently working on making Apache's [Teaclave TrustZone SDK][teaclave-tz], a Rust abstraction over libteec, work with more implementations than just OP-TEE. Part of that work is making its [FFI structure definitions][rust-defs], which currently hardcode OP-TEE's implementation-specific fields, generic over multiple implementations. The obvious way to do that is to use Rust generics, adding a type parameter that defines the concrete type of the `imp` field. But that requires me to split the OP-TEE implementation-specific fields into their own structure, resulting in this concrete type:

```c
typedef struct
{
	void* buffer;
	size_t size;
	uint32_t flags;
	struct {
	 	int id;
 	 	size_t alloced_size;
  		void *shadow_buffer;
 	 	int registered_fd;
 	 	union {
 	 		bool dummy;
 	 		uint8_t flags;
 	 	} internal;
	} imp;
} TEEC_SharedMemory;
```

Unfortunately, in C, **that type does not have the same layout as the one from tee_client_api.h shown above**. The nested struct changes how padding is calculated: on a 64-bit system, the type shown above has 4 bytes of padding between `flags` and `id` that libteec doesn't expect. (Note that I haven't verified the exact layouts empirically, but I'm pretty sure I'm right.)

I can work around this, but it means making each implementation-specific struct implement a common trait full of boilerplate getters and setters instead of just being able to access the fields directly from generic code. I'd prefer not to do that if I can avoid it.

[teaclave-tz]: https://github.com/apache/incubator-teaclave-trustzone-sdk
[rust-defs]: https://github.com/apache/incubator-teaclave-trustzone-sdk/blob/9eb7ff8eb883e15f32410d4424149a699b0964c3/optee-teec/optee-teec-sys/src/tee_client_api.rs#L99-L109

### Other implementations
There's at least one TEE that does follow my reading of the spec: Trustonic [defines][trustonic-def] `TEEC_SharedMemory` as follows:
```c
typedef struct TEEC_SharedMemory {
	void *buffer;
	size_t size;
	uint32_t flags;
	TEEC_SharedMemory_IMP imp;
} TEEC_SharedMemory;
```

[trustonic-def]: https://github.com/Trustonic/trustonic-tee-user-space/blob/e3b0b06025605b06fc1e19588098e5011f6afc83/MobiCoreDriverLib/ClientLib/public/GP/tee_client_api.h#L84-L89

**Comment by jenswi-linaro** [comment]
When we implemented this we read "<Implementation-Defined Type> imp;" in `TEEC_SharedMemory` as "here follow implementation specific fields". Feel free to propose a fix with a pull request to this git.

**Comment by tchebb** [comment]
Cool, thanks for confirming there's not some intentional reason for how we do it that I'm missing.

I probably won't have time to set up an OP-TEE dev environment and make/test a PR any time soon, sadly. I'm already on a bit of a tangent with the Teaclave modifications I'm making, and last night I discovered that the other implementation I'm trying to target actually has the same bug, which means I'd still need to workaround it in Rust even if OP-TEE gets fixed.

I'll leave this issue open as documentation and in case anyone else wants to take it on.
