### ISSUE TITLE
Make RPMB_EMU a runtime switch

### ISSUE THREAD

**Issue by jan-kiszka** [OP-TEE/optee_client#353]
Would it be possible to turn`RPMB_EMU` into a runtime switch for tee-supplicant? We are seeing even distro packages (https://packages.debian.org/bookworm/tee-supplicant) being built with the default `RPMB_EMU=1` which makes them useless for real use. Did anyone look into that already?

**Comment by jenswi-linaro** [comment]
I'm not aware of anyone looking into this. It sounds like a good idea though.

**Comment by jforissier** [comment]
> I'm not aware of anyone looking into this. It sounds like a good idea though.

+1

**Comment by jan-kiszka** [comment]
...and a rather simple one: already having a patch under test. Not looking nice, though, because I kept the `RPMB_EMU` built-time switch for now. We may discuss that when I propose it as PR.

**Comment by lsun100** [comment]
Sorry I wasn't aware of this thread. Also posted #355 for this purpose to remove the conditional compilation.

**Comment by jan-kiszka** [comment]
Only solved once https://github.com/OP-TEE/optee_client/pull/355 is done.
