### ISSUE TITLE
NVME RPMB support

### ISSUE THREAD

**Issue by jingdlu** [OP-TEE/optee_client#356]
Hi,

Shall we have NVME RPMB support in tee-supplicant?

**Comment by jforissier** [comment]
Hi @jingdlu,

> Shall we have NVME RPMB support in tee-supplicant?

I don't think so. An RPMB kernel driver has been proposed (see https://lkml.org/lkml/2023/7/21/1509) which would possibly support all kinds of RPMB partitions and solve a few more problems that `tee-supplicant` has. So I think the efforts should rather go into such a driver.

**Comment by jingdlu** [comment]
Hi @jforissier 

Thanks for sharing that kernel driver info. However, I found current RPMB operation in tee-supplicant is bound to eMMC device. Am I right?
If so, even there will be a unified RPMB driver, the tee-supplicant code should be changed accordingly? Even for RPMB operation in  optee_os? Like rpmb data frame pack?

**Comment by jforissier** [comment]
> Hi @jforissier
> 
> Thanks for sharing that kernel driver info. However, I found current RPMB operation in tee-supplicant is bound to eMMC device. Am I right?

Yes.

>  If so, even there will be a unified RPMB driver, the tee-supplicant code should be changed accordingly? Even for RPMB operation in optee_os? Like rpmb data frame pack?

Yes, if updating tee-supplicant to support NVME is trivial then we can do it. Otherwise I think it is acceptable to require NVME users to use the (yet to be implemented) RPMB driver instead.

**Comment by jingdlu** [comment]
Thanks for your reply.
