### ISSUE TITLE
tee-supplicant: "/foo:/bar::/baz" always gets prepended into the TEEC_LOAD_PATH

### ISSUE THREAD

**Issue by mikatammi** [OP-TEE/optee_client#357]
While investigating code, we noticed that because the way this is set up, the TEEC_TEST_LOAD_PATH which is set to "/foo:/bar::/baz", always gets prepended into the TA load path, even in production/release builds of OP-TEE.

https://github.com/OP-TEE/optee_client/blob/8533e0e6329840ee96cf81b6453f257204227e6c/tee-supplicant/src/tee_supplicant.c#L699C1-L709

I'd expect correct behaviour to only load from path that has been set compile time. (Also what happens if user of the Makefile does not set the TEEC_LOAD_PATH at all? Does it result in empty string or just compile error?)

**Comment by mikatammi** [comment]
Also I found leftovers from some `#ifdef CFG_TA_TEST_PATH`, which controls variables which aren't really used anywhere:
https://github.com/OP-TEE/optee_client/blob/master/tee-supplicant/src/teec_ta_load.c#L39-L53

**Comment by etienne-lms** [comment]
Indeed there are things to be removed. As you mentioned: `CFG_TA_TEST_PATH` related lines in _teec_ta_load.c_ and `TEEC_TEST_LOAD_PATH` in _tee_supplicant.c_. 

The default paths list is always set from build time config `CFG_TEE_CLIENT_LOAD_PATH`. Note `CFG_TEE_CLIENT_LOAD_PATH` is default set to _/lib_ from _config.mk_, _Android.mk_ and _tee-supplicant/CMakeLists.txt_.
This list can be overriden at runtime using `tee-supplicant` argument `--ta-dirs`.

Do you want to propose a P-R?

**Comment by mikatammi** [comment]
Well, for packaging the tee-supplicant I used this simple patch, which just removed all the TEEC_TEST_LOAD_PATH and CFG_TA_TEST_PATH related stuff altogether. https://github.com/OP-TEE/optee_client/pull/358 

But my next question would have been, does someone really need that functionality? If someone needs, then it of course needs to be fixed the right way

**Comment by mikatammi** [comment]
The PR has not yet been merged!
