### ISSUE TITLE
Fedora, arm-linux-gnuabihf-pkg-config: No such file or directory’

### ISSUE THREAD

**Issue by mardyr** [OP-TEE/optee_client#368]
Hi guys, 

I am building op-tee client on Fedora distro and I am getting ‘arm-linux-gnuabihf-pkg-config: No such file or directory’. I’ve tried multiple ways to install it on Fedora but I failed. I see that the package name is defined in flags.mk. Do you have any advices?

On the other hand I was able to build whole rootfs from build repo, so it should be a way

**Comment by etienne-lms** [comment]
This P-R https://github.com/OP-TEE/optee_client/pull/336 solved a dependency they did not need (here pkcs11/ACL support).
The crosstool pkg-config dates from https://github.com/OP-TEE/optee_client/pull/335.

**Comment by mardyr** [comment]
Hmm what are exactly the implications of WITH_TEEACL=0 from functionality point of view?

**Comment by mardyr** [comment]
Thanks for explanation. 
Have a great Monday!
Case closed :)
