### ISSUE TITLE
`ta_path` in `set_ta_path()` doesn't add NULL to last element. It may cause segmentation fault.

### ISSUE THREAD

**Issue by p870613** [OP-TEE/optee_client#374]
Hi, 

When I upgrade optee os, optee client and optee test from 3.21.0 to 4.1.0, I met some trouble that xtest failed in `8002` and others test.
I traced `optee os` and `optee client` code and found a bug.

In optee client, function `set_ta_path` in `tee-supplicant/src/tee_supplicant.c` used to initialize the `ta_path`, which stores `load ta path`.
However, **`ta_path` doesn't add NULL to last element.**

https://github.com/OP-TEE/optee_client/blob/afbd31d9592e8919cf2b6883e33d80fcc32ccdc2/tee-supplicant/src/tee_supplicant.c#L701

Otherwise, In the function `TEECI_LoadSecureModule`,  it uses loop to traverse `ta_path and must be `NULL` to terminate.
If there isn't the `NULL` end of `ta_path`, it can't terminate loop and continue to move next pointer.
**Finally, it casued the  segmentation fault.**
https://github.com/OP-TEE/optee_client/blob/afbd31d9592e8919cf2b6883e33d80fcc32ccdc2/tee-supplicant/src/teec_ta_load.c#L160C1-L172C14
```
int TEECI_LoadSecureModule(const TEEC_UUID *destination, void *ta,
			   size_t *ta_size)
{
	int res = TA_BINARY_NOT_FOUND;
	char **path = NULL;

	for (path = ta_path; *path; path++) { // if path is NULL, it will terminate. 
		res = try_load_secure_module(*path, destination, ta, ta_size);
		if (res == TA_BINARY_FOUND)
			break;
	}
	return res;
}
```

**It caused the `tee-supplicant` segmentation fault.**
log is below
```
DBG [8586] TEES:try_load_secure_module:104: Attempt to load /lib/optee_armtz/17e5e280-d12e-11e4-a41a-0002a5d5c51b.ta
DBG [8586] TEES:try_load_secure_module:113: failed to open the ta /lib/optee_armtz/17e5e280-d12e-11e4-a41a-0002a5d5c51b.ta TA-file
DBG [8586] TEES:try_load_secure_module:104: Attempt to load /lib/optee_armtz/17e5e280-d12e-11e4-a41a0002a5d5c51b.ta
DBG [8586] TEES:try_load_secure_module:113: failed to open the ta /lib/optee_armtz/17e5e280-d12e-11e4-a41a0002a5d5c51b.ta TA-file
Segmentation fault
```

I have two solutions to solve this bug.
1. Replace `malloc` with `calloc` in `set_ta_path()`
https://github.com/OP-TEE/optee_client/blob/afbd31d9592e8919cf2b6883e33d80fcc32ccdc2/tee-supplicant/src/tee_supplicant.c#L725

2. Add NULL to `ta_path` last element after loop.
https://github.com/OP-TEE/optee_client/blob/afbd31d9592e8919cf2b6883e33d80fcc32ccdc2/tee-supplicant/src/tee_supplicant.c#L733
```
	while ((new_path = strtok_r(p, ":", &saveptr))) {
		if (!supplicant_params.ta_load_path) {
			char full_path[PATH_MAX] = { 0 };

			path_len = snprintf(full_path, PATH_MAX, "%s/%s", new_path,
					    supplicant_params.ta_dir);
			if (path_len < 0 || path_len >= PATH_MAX)
				goto err_path;

			ta_path[n++] = strdup(full_path);
		} else {
			path_len = strnlen(new_path, PATH_MAX);
			if (path_len == PATH_MAX)
				goto err_path;

			ta_path[n++] = strdup(new_path);
		}

		p = NULL;
	}
        ta_dir[n++] = NULL; // <---- add this line
```

If you need, I can launch PR to fix this bug.

Thanks !!

**Comment by jforissier** [comment]
Hi @p870613, thanks for reporting this.

```
}
        ta_dir[n++] = NULL; // <---- add this line
```
You mean `ta_path` not `ta_dir` I suppose? I suggest:
```
	ta_path[n] = NULL; /* Terminator */
```

**Comment by p870613** [comment]
Yes, this is a typo.
