### ISSUE TITLE
How to get Status ready of tee-supplicant

### ISSUE THREAD

**Issue by embetrix** [OP-TEE/optee_client#378]
I use Optee PKCS11 TA to store key for my rootfs disk encryption(Luks), I want to use it from my Initramfs to retrieve the key and inject it to Crypsteup as follow:

```
start-stop-daemon -S -b --exec /usr/sbin/tee-supplicant
# Avoid sleep here
# Load Key file  and inject it to cryptsetup
pkcs11tool --login --read-object --type data --label myKey | cryptsetup luksOpen /dev/mmcblk0p2 crypt-rootfs  --key-file=-
start-stop-daemon -K  --exec /usr/sbin/tee-supplicant
```
This seems to be working but not all the time, sometime **tee-supplicant** need some time to settle, I can put a delay before access PKCS11 storage but I like to avoid unnecessary delays to speed up the boot process.

How can I get the readiness status of  **tee-supplicant** ( PKCS11 TA loaded and ready to work with) ?

**Comment by jforissier** [comment]
Perhaps try starting tee-supplicant with `/usr/sbin/tee-supplicant -d`. The `-d` argument will make it fork but only return when the service is ready (at least it was designed for that).
