### ISSUE TITLE
Questions about session keys in PKCS#11 driver demo

### ISSUE THREAD

**Issue by D1aoBoomm** [OP-TEE/optee_client#379]
Hello, I'm testing [PKCS11 Driver Demo](https://optee.readthedocs.io/en/latest/building/userland_integration.html) and it works. I understand and am sure that the private key for signing self-signed certificates is stored in the TEE.
But would like to know if the session key (established in following step) is in the secure memory of the TEE or in REE.
```OPENSSL_CONF=optee_hsm.conf openssl s_client -engine pkcs11 -connect 192.168.178.34:9876 -cert mykey_selfsigned_cert.pem -keyform engine -key label_mykey```

I am sorry to bother you developers. I didn't find an answer to this, maybe it's better to ask the Openssl developers.

**Comment by etienne-lms** [comment]
The session key will be stored and used in REE memory. With this setup, it's only the asymmetric key that is stored in TEE memory.

**Comment by D1aoBoomm** [comment]
Thank you for your valuable help! @etienne-lms 
I would like to know if there is a way to generate session key inside TEE? I'd appreciate it if you can answer me!

**Comment by etienne-lms** [comment]
I don't think OpenSSL supports this. I found no OpenSSL configuration resource related to such a feature even if technically speaking the PKCS#11 API allows that.

**Comment by D1aoBoomm** [comment]
I sincerely express my gratitude to you!
I'm closing this issue.
