### ISSUE TITLE
Issue with TEE-Suplicant and RPMB on Rock PI4

### ISSUE THREAD

**Issue by kpr-ouster** [OP-TEE/optee_client#384]
I am building for Rock PI4 with the following flags

```
CFG_REE_FS=n 
CFG_RPMB_FS=y 
CFG_RPMB_WRITE_KEY=y or n 
BR2_PACKAGE_OPTEE_CLIENT_EXT_RPMB_EMU=n
```
I have a 64GB eMMC module into which a generated RPMB key has been programmed (by OP-TEE) and I have confirmed that the key has been correctly programmed using MMC utils and the Optee example secure storage app.

The problem is that from a cold boot the Optee example secure storage app fails with the following output

```
# optee_example_secure_storage 
Prepare session with the TA
D/TC:? 0 tee_ta_init_pseudo_ta_session:297 Lookup pseudo TA f4e750bb-1437-4fbf-8785-8d3580c34994
D/TC:? 0 ldelf_load_ldelf:110 ldelf load address 0x40007000
D/LD:  ldelf:142 Loading TS f4e750bb-1437-4fbf-8785-8d3580c34994
D/TC:? 0 ldelf_syscall_open_bin:163 Lookup user TA ELF f4e750bb-1437-4fbf-8785-8d3580c34994 (early TA)
D/TC:? 0 ldelf_syscall_open_bin:167 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:163 Lookup user TA ELF f4e750bb-1437-4fbf-8785-8d3580c34994 (REE)
D/TC:? 0 ldelf_syscall_open_bin:167 res=0
D/TC:? 0 tee_rpmb_init:1115 RPMB: Syncing device information
D/TC:? 0 tee_rpmb_init:1123 RPMB: RPMB size is 128*128 KB
D/TC:? 0 tee_rpmb_init:1124 RPMB: Reliable Write Sector Count is 1
D/TC:? 0 tee_rpmb_init:1151 RPMB INIT: Deriving key
I/TC: RPMB: Using generated key
D/TC:? 0 tee_rpmb_init:1166 RPMB INIT: Verifying Key
E/TC:? 0 tee_rpmb_verify_key_sync_counter:1014 Verify key returning 0xffff0006
E/TC:? 0 tee_rpmb_init:1177 Verify key failed!
E/TC:? 0 tee_rpmb_init:1178 Make sure key here matches device key
E/LD:  copy_section_headers:1135 sys_copy_from_ta_bin
E/TC:? 0 ldelf_init_with_ldelf:152 ldelf failed with res: 0xffff0006
D/TC:? 0 tee_ta_open_session:686 init session failed 0xffff0006
```
If I then kill and restart the tee-supplicant daemon the Optee example secure storage app runs to completion. 

Looking in the tee supplicant log I find the issue in function mmc_rpmb_fd()

`ERR [141] TSUP:mmc_rpmb_fd:170: Could not open /dev/mmcblk0rpmb (Permission denied)`

The device node is present and mmc utils has no problems reading from the RPMB. 

Any ideas how to debug further?
 
PS:

Impacts xtest too

After power on/reset ...
```
708 subtests of which 273 failed
105 test cases of which 77 failed
0 test cases were skipped
```
After daemon restart ...
```
29683 subtests of which 0 failed
105 test cases of which 0 failed
0 test cases were skipped
```

**Comment by jenswi-linaro** [comment]
The log says that the key programmed into RPMB doesn't match what OP-TEE has derived. You may have programmed the test key `CFG_RPMB_TESTKEY=y` earlier so that is what you need now too. Or someone/something else had programmed the RPMB key before you could write the key OP-TEE would use.

**Comment by kpr-ouster** [comment]
The log says key verification fails because of cause 0xffff0006 (TEEC_ERROR_BAD_PARAMETERS). Digging deeper I found the cause of this to be in tee-supplicant

_ERR [141] TSUP:mmc_rpmb_fd:170: Could not open /dev/mmcblk0rpmb (Permission denied)_

When I then kill the tee-supplicant daemon and restart it then everything works as expected. The key is correctly programmed and all the xtest cases succeed

**Comment by kpr-ouster** [comment]
This is a permissions problem, /dev/mmcblk0rpmb should belong to group tee

At boot tee-supplicant is started by the tee user

```
# ps | grep tee-supplicant
  157 tee      /usr/sbin/tee-supplicant -d /dev/teepriv0

```
That's fine for /dev/tee0 but not so much for /dev/mmcblk0rpmb

```
# ls -al /dev/mmcblk0rpmb 
crw-------    1 root     root      234,   0 Jan  1 00:00 /dev/mmcblk0rpmb
```

```
# ls -al /dev/tee*
crw-rw----    1 root     teeclnt   247,   0 Jan  1 00:00 /dev/tee0
crw-rw----    1 root     tee       247,  16 Jan  1 00:00 /dev/teepriv0

```
When I (root) kill tee-supplicant and restart it:
```
# ps | grep tee-supplicant
  197 root     /usr/sbin/tee-supplicant -d /dev/teepriv0

```

**Comment by jforissier** [comment]
> This is a permissions problem, /dev/mmcblk0rpmb should belong to group tee

You may be able to do this by writing a custom `udev` rule as `/etc/udev/rules.d/rpmb.rules`. Once you have the proper parameters, store the file as `build/br-ext/board/rockpi4/overlay/etc/udev/rules.d/rpmb.rules` in the OP-TEE build environment and it should be picked up automatically during the build.

If you get something working please share as a pull request in https://github.com/OP-TEE/build/. Thanks!

**Comment by kpr-ouster** [comment]
l was thinking of adding something to /etc/init.d/S30optee

```
	printf 'Set permissions on %s: ' "/dev/mmcblk*rpmb"
	[ -e /dev/mmcblk0rpmb ] && chown root:tee /dev/mmcblk0rpmb && \
		chmod 0660 /dev/mmcblk0rpmb
```

udev would be cleaner but is it enabled? If so then why is /etc/init.d/S30optee changing the group of /dev/teeclnt and /dev/tee0?

Shouldn't this be issue for all platforms and not just Rock Pi4?

**Comment by jforissier** [comment]
> l was thinking of adding something to /etc/init.d/S30optee
> 
> ```
> 	printf 'Set permissions on %s: ' "/dev/mmcblk*rpmb"
> 	[ -e /dev/mmcblk0rpmb ] && chown root:tee /dev/mmcblk0rpmb && \
> 		chmod 0660 /dev/mmcblk0rpmb
> ```
> 
> udev would be cleaner but is it enabled? 

I believe so. I found `udev.conf in the build output directory and `out-br/.config` contains `BR2_PACKAGE_EUDEV=y`.

> If so then why is /etc/init.d/S30optee changing the group of /dev/teeclnt and /dev/tee0?

No particular reason. Having a `udev` rule would be cleaner.

> Shouldn't this be issue for all platforms and not just Rock Pi4?

Certainly, for all platforms having a real RPMB.
