### ISSUE TITLE
tee-supplicant@.service: Getting build error in case yocto uses sysvinit and don't use usrmerge 

### ISSUE THREAD

**Issue by sahilnxp** [OP-TEE/optee_client#393]
Getting following error when compiling optee-client-ls with this [patch ](https://github.com/OP-TEE/optee_client/commit/bf0d02758696ee7a9f7af9e95f85f5c238d0e109)through yocto.
Including the meta-arm optee-client.inc in optee-client-ls
My yocto environment has sysvinit and don't use usrmerge.

```
ERROR: optee-client-4.4.0+git-r0 do_package: QA Issue: optee-client: Files/directories were installed but not shipped in any package:
  /usr/lib/systemd
  /usr/lib/systemd/system
  /usr/lib/systemd/system/tee-supplicant@.service
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
optee-client: 3 installed and not shipped files. [installed-vs-shipped]
```

[Recipe ](https://git.yoctoproject.org/meta-arm/tree/meta-arm/recipes-security/optee/optee-client.inc?h=scarthgap#n27)is installing the tee-supplicant@.service in {systemd_system_unitdir}  which is in my case is /lib/
[OP-TEE client src](https://github.com/OP-TEE/optee_client/blob/master/tee-supplicant/CMakeLists.txt#L122) is installing it in /usr/lib/ - Which I think is causing the issue..

We just added the do_install: append() in our optee-client-ls recipe which is just deleting `/usr/lib/systemd` and this error disappars, but that is a workaround only for such environments.

Do we need to put some check in CMakefile so that it only gets installed on systemd enabled systems ?

cc: @thochstein

**Comment by jforissier** [comment]
CC: @mikkorapeli-linaro

**Comment by mikkorapeli-linaro** [comment]
Hi, sorry about the transitional issue. I plan to port this patch to meta-arm and remove the existing service file. The systemd service file will only be installed when systemd distro feature is selected. The bbappend workaround on your side is the right thing to do, IMO.

I did not add a optee-client side CMake flag to disable systemd support. Also the systemd sd-notify support is enabled unconditionally, though that does not show up as build/install or runtime problems if systemd is not available.

**Comment by sahilnxp** [comment]
> I did not add a optee-client side CMake flag to disable systemd support. Also the systemd sd-notify support is enabled unconditionally, though that does not show up as build/install or runtime problems if systemd is not available.

IIUC, In our case it is throwing an error, I think it is better to have CMake config flag to disable systemd support, currently it is installing these files by default. User can keep this flag enabled/disabled based on the environment he is using.

**Comment by mikkorapeli-linaro** [comment]
Upstream meta-arm recipe changes are in https://lists.yoctoproject.org/g/meta-arm/message/6191

**Comment by thochstein** [comment]
Hi @mikkorapeli-linaro, the QA error only happens for our QorIQ devices, while our i.MX devices have no such problem. The difference seems to be that for QorIQ we do not use `usrmerge`. In this case, the cmake does install the service file to `/usr/lib/systemd/system`, while bitbake expects `/lib/systemd/system`.

**Comment by mikkorapeli-linaro** [comment]
Which yocto branch are you building? AFAIK, usrmerge is mandatory in latest poky master branch when systemd is selected.

**Comment by sahilnxp** [comment]
@mikkorapeli-linaro We are currently using `scarthgap `branch.

**Comment by mikkorapeli-linaro** [comment]
Hmm, usrmerge feature is really mandatory with systemd https://git.yoctoproject.org/poky/tree/meta/conf/distro/include/init-manager-systemd.inc?h=scarthgap
So your configuration enables systemd but disables usrmerge on scarthgap?

**Comment by sahilnxp** [comment]
No, qoriq platforms don't use `systemd`, it uses `sysvinit `without `usrmerge`.

**Comment by mikkorapeli-linaro** [comment]
Ok, then I think the meta-arm patch change will cover your use case as it doesn't install the systemd file if systemd distro feature is not selected. Install paths are always standard CMake ones which expect usrmerge. I'm not sure if meta-arm scarthgap branch will accept the same patch but I can try.

**Comment by sahilnxp** [comment]
I am not so much familiar with CMAKE, but is there any variable in CMAKE, that can adjust to /usr/lib or /lib/ is usrmerge is enabled or not ?
If there is one, we can use it [here ](CMAKE_INSTALL_LIBDIR) in place of `CMAKE_INSTALL_LIBDIR`

**Comment by mikkorapeli-linaro** [comment]
I don't think CMake supports /lib install paths via any variable. It's also about using the install prefix or not and for libdir it should be used.

As said, your use case is covered by the meta-arm side optee-client recipe changes. They remove the systemd service file if systemd distro feature is not selected.

**Comment by thochstein** [comment]
Given that `usrmerge` is required now for `systemd`, I think your recipe change is sufficient.
