### ISSUE TITLE
Makefile hardcoded /lib breaks when distro uses /lib64

### ISSUE THREAD

**Issue by koenkooi** [OP-TEE/optee_client#64]
As the subject says, if the distro uses /lib64 libtee*.so will get installed in the wrong place and won't be found be e.g. optee-test.

**Comment by fboudra** [comment]
The use case is multilib enabled distributions. See also https://review.linaro.org/#/c/15766 for our workaround until this issue is fixed.

**Comment by jbech-linaro** [comment]
We used to have different paths, but when we stepped up to GCC5.x, it seemed like it always default to `/lib/`, so we made a change roughly a year ago. Does anyone of you know if one can query gcc to figure out where it would like to see the libs etc to be placed? I.e, something similar to: `$ gcc --print-file-name=include` and friends?

**Comment by jforissier** [comment]
@jbech-linaro the path where shared libraries should be installed ultimately depends on the distro, like @koenkooi said. The compiler has little to do with this (well, there is probably a default path embedded by the linker into the ELF files, I'm not sure but IMO it doesn't really matter).

The only viable option I see is to add a configuration variable to play a similar role as the autoconf "--libdir" option (`./configure --libdir=/lib64 ...`), let's call it `LIBDIR`. And while we're at it, let's do the same for `bin` and `include` and whack in `$(DESTDIR)` to help choose the staging location.

@koenkooi would that work for you?

```diff
diff --git a/Makefile b/Makefile
index 93bfa0e..3805dc6 100644
--- a/Makefile
+++ b/Makefile
@@ -12,6 +12,10 @@ export VPREFIX
 
 EXPORT_DIR ?= $(O)/export
 
+LIBDIR ?= $(DESTDIR)$(EXPORT_DIR)/lib
+INCLUDEDIR ?= $(DESTDIR)$(EXPORT_DIR)/lib
+BINDIR ?= $(DESTDIR)$(EXPORT_DIR)/lib
+
 CFG_SQL_FS ?= n
 CFG_TA_GPROF_SUPPORT ?= n
 
@@ -123,11 +127,11 @@ checkpatch-all-files: checkpatch-pre-req
 distclean: clean
 
 copy_export: build
-       mkdir -p ${EXPORT_DIR}/lib ${EXPORT_DIR}/include ${EXPORT_DIR}/bin
-       cp ${O}/libteec/libteec.so* ${EXPORT_DIR}/lib
-       if [ "$(BUILD-LIBSQLFS)" ]; then cp ${O}/libsqlfs/libsqlfs.so* ${EXPORT_DIR}/lib; fi
-       cp ${O}/tee-supplicant/tee-supplicant ${EXPORT_DIR}/bin
-       cp public/*.h ${EXPORT_DIR}/include
+       mkdir -p ${LIBDIR} ${INCLUDEDIR} ${BINDIR}
+       cp ${O}/libteec/libteec.so* ${LIBDIR}
+       if [ "$(BUILD-LIBSQLFS)" ]; then cp ${O}/libsqlfs/libsqlfs.so* ${LIBDIR}; fi
+       cp ${O}/tee-supplicant/tee-supplicant ${BINDIR}
+       cp public/*.h ${INCLUDEDIR}
 
 ifeq ($(CFG_SQL_FS),y)
 

```

**Comment by koenkooi** [comment]
That would work, although traditionally it would be more like this:

```
LIBDIR ?= $(EXPORT_DIR)/lib
[..]
install -d $(DESTDIR)$(LIBDIR)
```

That makes it possible to reuse LIBDIR for other things during the build.

**Comment by jforissier** [comment]
@koenkooi you're right, I wrote the above by memory and it is some time since I last played with autoconf stuff ;)
OK I'll make a PR shortly.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_client/pull/65

**Comment by jbech-linaro** [comment]
@koenkooi @fboudra the fix has been merged, so if update optee_client to latest it shall hopefully work.

**Comment by fboudra** [comment]
Thanks for the quick turnaround. We'll update the recipe on our end and get rid of the workaround.
