### ISSUE TITLE
why do we use type s64 to define fd in the struct tee_ioctl_shm_register_fd_data?

### ISSUE THREAD

**Issue by prime-zeng** [OP-TEE/optee_client#70]
@etienne-lms  Currently the fd is used as s32 in both optee_client and optee-driver, why define it as type s64?

**Comment by etienne-lms** [comment]
hello @prime-zeng. I have crosscheck current implementation in optee_client and in the linux kernel optee driver. file descriptor are `int` in both  user and kernel lands and are `_s64` in the uapi.

Maybe you refer to old references the "register shm from fd" implementation proposal.
Or maybe you looked at the `id` field of `struct tee_ioctl_shm_register_fd_data` ? This field hold an ID set by the driver to refer the shm buffer. It is not a file descriptor, just an ID.

The optee_client and linux driver implementation of it is now merged.
Could you check again ?

**Comment by etienne-lms** [comment]
@prime-zeng: reading back your question i find that i have answer it the wrong way. Below is a more accurate answer i hope.

Using type `__s64` for userland and kernel land signed integers allows to support all flavours of 32bit and 64bit worlds with modify the API. That's the goal of the UAPI is think.

**Comment by prime-zeng** [comment]
@etienne-lms , yes ,__s64 is more compatible, but what i am worried about  is the security:
1. From the optee-client api to uapi,  there is int to _s64 conversion, and that is safe.
2. From uapi to optee-driver, there is _s64 to int conversion which is not safe. 
And uapi can be called other then the optee-client, we can't make sure it is under control. 

I can't see any way to hack into the optee-driver now,  i just think that is a possible weak point.

**Comment by etienne-lms** [comment]
> From uapi to optee-driver, there is `__s64` to int conversion which is not safe.

Unsafe would be to convert 64bit full range integer into a 32bit integer, right?

If the kernel in 32bit, then userland is also 32bit:    '32bit int' => '64bit' => '32bit int' is safe.
If the kernel in 64bit, then userland can be 32bit or 64bit: '32bit or 64bit int' => '64bit' => '64bit int' is safe.
So i think it the current TEE uapi  is safe.

**Comment by prime-zeng** [comment]
@etienne-lms   For the current legal usecase, i think it is safe, but for example:
APP(64bit)--->UAPI(64bit)---->OP-TEE driver(32bit) is maybe not safe.

**Comment by jenswi-linaro** [comment]
A 32-bit kernel can't have a 64-bit user space.

**Comment by prime-zeng** [comment]
No, 32bit and 64bit means the data type.  Both the client-api and the optee driver use s32 data type,  but the uapi use s64 data type.       1. client-api(s32)--->uapi(s64)--->optee driver(s32)  is safe. 2. app(s64)---->uapi(s64)---->optee driver(s32) is not safe.

**Comment by jenswi-linaro** [comment]
The value of `fd` originates from an `int` in the kernel so it should always fit in an `int`. If it doesn't then user space is up to something and could just as well supply whatever value of `fd` it wanted it to be interpreted like directly instead of relying on a truncated number.

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
