### ISSUE TITLE
tee_client_api.h provides incorrect max shared memory size

### ISSUE THREAD

**Issue by LKostyra** [OP-TEE/optee_client#88]
In tee_client_api.h there is an [incorrect constant for max shared memory size](https://github.com/OP-TEE/optee_client/blob/master/public/tee_client_api.h#L46):
`#define TEEC_CONFIG_SHAREDMEM_MAX_SIZE 0x8000`

According to GP API specification (and the comment above the constant), the limit should be equal to 512 kB (0x8000**0**), now it is 32kB, which in result does not allow you to allocate higher memory sizes for bigger data.

**Comment by jforissier** [comment]
Hi @LKostyra ,

You're right, that's obviously a typo and I'm surprise we did not found it sooner. We should probably add a test to our test suite.

Would you please create a pull request to fix this bug?

**Comment by jforissier** [comment]
Closing this issue since pull request has been merged.
