### ISSUE TITLE
logic about tee_supplicant to create new thread

### ISSUE THREAD

**Issue by shuaifengyun** [OP-TEE/optee_client#97]
In the function of process_one_request, Firstly, main function will call process_one_request to get request from TA  by reading the request list in OP-TEE driver. If tee_supplicant get request data from driver, main function will call spawn_thread function to create a new thread, and the new thread also will call process_on_request to continue to get request. After that, main function will handle the request and loop again. It's like main function will create new thread every time when main receive the request from TA then handle request and loop again. Is there any wrong by this logic?

**Comment by jenswi-linaro** [comment]
`process_one_request()` is only supposed to spawn new threads if there's no idle threads. The threads are spawned in advance to make sure that there's at least one thread available to serve the next request in case the last request blocks for some time.

When watching tee-supplicant in action I've noticed that it usually spawns one or two more threads than what's strictly necessary. After a few requests it stabilizes and doesn't spawn any more threads.

Have you noticed a different behavior?

**Comment by shuaifengyun** [comment]
OK, thanks, I got it, when thread receive the request from TA, thread will decrease the waiter number, and if the waiter number is less than zero, the process_one_request will return false, and thread will end itself.

**Comment by jenswi-linaro** [comment]
No threads are supposed to end themselves, unless there's some error that can't be handled.

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
